### ISSUE TITLE
AutoText

### ISSUE THREAD

**Issue by CodeOfDark** [ImpactDevelopment/ImpactClient#553] opened 2018-04-25 19:17 UTC
its will be pretty much nice if there's a AutoText
e.g: I pressed key "alt + g" its will auto text GG and send it on Chat

**Comment by SuperOP535** [comment] 2018-04-25 19:17
macro

**Comment by ZeroMemes** [comment] 2018-04-25 19:24
Duplicate of #153

**Closed by ZeroMemes** 2018-04-25 19:24 UTC
Labels: Duplicate
