### ISSUE TITLE
Blocks per Second Counter

### ISSUE THREAD

**Issue by RohanG0407** [ImpactDevelopment/ImpactClient#597] opened 2018-05-27 02:39 UTC
## Add a BPS Counter Above the Coords in Bottom Right Corner

- There is no way to tell how fast I am going with **Entity Speed** at the current moment

- It's a very simple addition but would be very helpful in many scenarios

Hoping it can be added for Impact 4.3

**Comment by LeafHacker** [comment] 2018-05-27 02:43
Duplicate of #554

**Closed by LeafHacker** 2018-05-27 02:43 UTC
