### ISSUE TITLE
Make Riding work with boats

### ISSUE THREAD

**Issue by koraseeq** [ImpactDevelopment/ImpactClient#690] opened 2018-08-14 12:23 UTC
Make Riding work with boats

**Comment by ChristoferMinestar** [comment] 2018-08-14 12:51
It does... Just really buggy on servers

**Comment by SuperOP535** [comment] 2018-08-14 15:05
Duplicate of #654

**Comment by SuperOP535** [comment] 2018-08-14 15:06
Actually, I'm unsure because of the amount of information given

**Comment by VitorISs** [comment] 2018-08-14 15:53
some bugs about boats and riding have already been fixed, i think in 4.4 it's everything fine
i can't really see the point of this issue

**Comment by ChristoferMinestar** [comment] 2018-08-14 20:07
Wait kinda unrelated but does Impact have a beta? Because 4.4 fixes a lot of bugs that would be the only reason I'm tempted to get future.

**Comment by LeafHacker** [comment] 2018-08-18 23:06
This seems like a duplicate as above. Even if not it doesn't have enough detail to be useful, so closing either way.

**Closed by LeafHacker** 2018-08-18 23:06 UTC
Labels: Need more info
