### ISSUE TITLE
Mod that will highlight and save new chunks generated by your player.

### ISSUE THREAD

**Issue by GlitchHead** [ImpactDevelopment/ImpactClient#591] opened 2018-05-20 03:06 UTC
This mod will highlight the chunk boarder of new chunks that are generated by your player and save them to file per server. This is highly useful because we could use it to follow paths of old chunks that another player generated and find their base. If you add the ability for the mod to save the chunks you generated to file or something it will be less likely you would get your new chunks mixed up with the old chunks your following if you happen to restart the client or lag out.

**Comment by LordQuadrato** [comment] 2018-05-20 09:36
Duplicate of #555. Although the save function is not described there. Maybe comment on the other issue.

**Comment by LeafHacker** [comment] 2018-05-21 15:58
Duplicate of #555

Please feel to comment any additional input over there (e.g. saving new chunck positions locally)

**Closed by LeafHacker** 2018-05-21 15:58 UTC
