### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by CollierPlays** [ImpactDevelopment/ImpactClient#659] opened 2018-07-19 14:29 UTC
Every time i jump,sprint, and hit a block my game seems to crash
Here's a picture of my modules and crash report, i don't know the exact steps to reproduce.
[crash-2018-07-19_09.15.20-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2210330/crash-2018-07-19_09.15.20-client.txt)
![image](https://user-images.githubusercontent.com/24845326/42948939-3799a0c4-8b36-11e8-9b2b-b2f524914fe5.png)

**Comment by LordQuadrato** [comment] 2018-07-19 14:36
This is a duplicate of #653, same crash.
Disabe `AutoTool` for now.

**Closed by LordQuadrato** 2018-07-19 14:36 UTC
