### ISSUE TITLE
Impact latest version,1.12.2 crashing on the second try

### ISSUE THREAD

**Issue by noobsplicer** [ImpactDevelopment/ImpactClient#1517] opened 2019-08-10 09:26 UTC
ok so when i first installed impact, it worked normally, but when i logged off and logged back on it crashed. it seems that its a problem with the texture. i tried replacing the texture, deleting the files and reinstalling, but it didn't work. i dont have optifine installed. my launcher log is long so ill just attach the file

**To Reproduce**
idk it only seems to happen to me

**Expected behavior**
i expected it to work

 

- Impact Version: 4.7.2, 1.12.2
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: none because I can't open it
- Operating System: Windows 10 64bit
[launcher_log.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3488712/launcher_log.txt)

**Additional context**
it works the same with optifine

[crash-2019-08-10_23.14.38-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/3489262/crash-2019-08-10_23.14.38-client.txt)

**Comment by EmeraldSnorlax** [comment] 2019-08-10 09:31
> tried replacing the logo

or whatever file `2378311fabbccae299383fa84b1c8126b4c497ce` points to ^^

**Comment by RelievedStudios** [comment] 2019-08-10 14:56
have you deleted and reinstalled the instance?

**Comment by noobsplicer** [comment] 2019-08-10 14:57
i deleted and reinstalled all the files, and minecraft included

**Comment by RelievedStudios** [comment] 2019-08-10 15:09
maybe try setting a different game dir? 
![image](https://user-images.githubusercontent.com/46948241/62823493-a065d580-bbd4-11e9-8862-290ff9d5d767.png)

**Comment by noobsplicer** [comment] 2019-08-10 15:31
worked on the first try but didnt on the second try

**Comment by RelievedStudios** [comment] 2019-08-10 15:32
do you have any other mods installed or resource packs?

**Comment by noobsplicer** [comment] 2019-08-10 15:33
i have 2 shaders and stratum 128x128 resource pack

**Comment by RelievedStudios** [comment] 2019-08-10 15:34
try without optifine?

**Comment by noobsplicer** [comment] 2019-08-10 15:35
![image](https://user-images.githubusercontent.com/53967412/62823770-88bf2a80-bb9d-11e9-8864-d12d337bf0d8.png)
if you mean this part i already installed it without of

**Comment by RelievedStudios** [comment] 2019-08-10 15:35
> > tried replacing the logo
> 
> or whatever file `2378311fabbccae299383fa84b1c8126b4c497ce` points to ^^

what did this file point to?

**Comment by noobsplicer** [comment] 2019-08-10 15:36
.minecraft/Impact/assets

**Comment by noobsplicer** [comment] 2019-08-10 15:37
there's multiple files with similar names to that

**Comment by RelievedStudios** [comment] 2019-08-10 15:40
`impact.4k` try deleting that

**Comment by noobsplicer** [comment] 2019-08-10 15:41
where's that

**Comment by RelievedStudios** [comment] 2019-08-10 15:43
wait never mind, have you tried setting more then 2G ram?

**Comment by noobsplicer** [comment] 2019-08-10 15:44
i wanted to do that but i dont know how to do that in this launcher

**Comment by RelievedStudios** [comment] 2019-08-10 15:45
![nRblWWUWMk](https://user-images.githubusercontent.com/46948241/62823869-a6aa8080-bbd9-11e9-84c7-3fc79ef5d275.gif)

**Comment by noobsplicer** [comment] 2019-08-10 15:46
set it to 5g now, ill try

**Comment by RelievedStudios** [comment] 2019-08-10 15:47
how much does your system have?

**Comment by noobsplicer** [comment] 2019-08-10 15:47
16

**Comment by RelievedStudios** [comment] 2019-08-10 15:47
might as well set it for 8

**Comment by noobsplicer** [comment] 2019-08-10 15:47
okay, also 5 didnt work aswell

**Comment by noobsplicer** [comment] 2019-08-10 15:48
nope 8 doesnt work

**Comment by RelievedStudios** [comment] 2019-08-10 16:01
I cant seem to find the error exactly

**Comment by noobsplicer** [comment] 2019-08-10 16:01
im dumb basically so you should try looking for the easy problems to solve

**Comment by rdmir3** [comment] 2019-08-11 08:21
Delete `impact/assets` on every launch.

**Comment by noobsplicer** [comment] 2019-08-11 17:47
bruh.

**Comment by StijnSimons** [comment] 2019-08-12 11:34
Can we have the full log? Not just the crash

**Comment by noobsplicer** [comment] 2019-08-12 11:35
the launcher log and crash log is there, what more can i add? if its gonna help i will

**Comment by StijnSimons** [comment] 2019-08-12 11:37
`%appdata%\.minecraft\latest.log`. The launcher log still contains launcher stuff.

**Comment by noobsplicer** [comment] 2019-08-12 11:38
what does the latest.log contain?

**Comment by StijnSimons** [comment] 2019-08-12 11:40
The game's log??

**Comment by noobsplicer** [comment] 2019-08-12 11:41
ok editing it in now

**Comment by StijnSimons** [comment] 2019-08-12 11:53
thats a log without running impact...

**Comment by noobsplicer** [comment] 2019-08-12 11:54
i deleted it and tried to play with impact again

**Comment by noobsplicer** [comment] 2019-08-12 11:58
how do i put useful information in it lmao

**Comment by StijnSimons** [comment] 2019-08-12 12:24
run impact and wait till it crashes, then put in the log

**Comment by noobsplicer** [comment] 2019-08-12 12:28
ok im deleting latest.log and running mc with impact and then editing the latest.log in again

**Comment by noobsplicer** [comment] 2019-08-12 12:29
[latest.log](https://github.com/ImpactDevelopment/ImpactClient/files/3492313/latest.log)

i hope this is it

**Comment by noobsplicer** [comment] 2019-08-12 12:38
[latest.log](https://github.com/ImpactDevelopment/ImpactClient/files/3492360/latest.log)

**Comment by StijnSimons** [comment] 2019-08-12 12:39
Still the same but aight doesnt matter, i'll do it with this

**Comment by noobsplicer** [comment] 2019-08-12 12:39
im retarded

**Comment by StijnSimons** [comment] 2019-08-12 12:40
Its pretty much up to Impact developers to fix this. Noone has access to the source.

**Comment by noobsplicer** [comment] 2019-08-12 12:41
bruh is it that hard lmao

**Comment by noobsplicer** [comment] 2019-08-12 12:42
who's the best dev so i can ask for help

**Comment by StijnSimons** [comment] 2019-08-12 12:44
No need to ask. They read issues so just keep this open. Don't start asking them cause that would annoy them.

**Comment by noobsplicer** [comment] 2019-08-12 12:45
ok good, when do u think i will get a fix tho

**Comment by LeafHacker** [comment] 2019-08-13 21:05
Duplicate of #1460

**Closed by LeafHacker** 2019-08-13 21:05 UTC
Labels: Bug

**Comment by rdmir3** [comment] 2019-08-14 06:22
Before every launch of the game, open command prompt and paste the following and press enter:

```
rmdir %appdata%\.minecraft\impact\assets /s /q
```

**Comment by noobsplicer** [comment] 2019-08-14 08:38
it doesnt work, system cannot find the file specified

**Comment by noobsplicer** [comment] 2019-08-18 10:12
ooh new update but still no progress

**Comment by clerickx** [comment] 2020-10-05 06:34
reinstall minecraft

**Comment by clerickx** [comment] 2020-10-05 06:35
might work

**Comment by clerickx** [comment] 2020-10-05 06:35
or delete mod files

**Comment by l1ving** [comment] 2020-10-05 11:59
This is over a year old 🗿
