### ISSUE TITLE
Crash (with log)

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#167] opened 2017-08-26 09:52 UTC
11:50:27 | bkp | Connecting to anarchy.daporkchop.net, 25565
-- | -- | --
11:50:30 | bhz | Unreported exception thrown! java.lang.NullPointerException 	at me.zero.clarinet.d0.lambda$new$0(d0.java) 	at me.zero.clarinet.d0$$Lambda$103/372630073.invoke(Unknown Source) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:77) 	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98) 	at me.zero.alpine.EventManager$$Lambda$82/1669068412.accept(Unknown Source) 	at java.util.ArrayList.forEach(ArrayList.java:1249) 	at me.zero.alpine.EventManager.post(EventManager.java:98) 	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:18) 	at bhz.handler$onTick$zzj000(SourceFile:3172) 	at bhz.t(SourceFile) 	at bhz.az(SourceFile:1000) 	at bhz.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I left in nether last time

EDIT: IT HAPPEND AGAIN! (another server)

12:49:27 | bkp | Connecting to 9b9t.com, 25565
-- | -- | --
12:49:29 | biz | [CHAT]
12:49:31 | bhz | Unreported exception thrown! java.lang.NullPointerException 	at me.zero.clarinet.d0.lambda$new$0(d0.java) 	at me.zero.clarinet.d0$$Lambda$103/648012542.invoke(Unknown Source) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:77) 	at me.zero.alpine.EventManager.lambda$post$6(EventManager.java:98) 	at me.zero.alpine.EventManager$$Lambda$82/839378654.accept(Unknown Source) 	at java.util.ArrayList.forEach(ArrayList.java:1249) 	at me.zero.alpine.EventManager.post(EventManager.java:98) 	at me.zero.client.api.event.CAPIEventManager.post(CAPIEventManager.java:18) 	at bhz.handler$onTick$zzj000(SourceFile:3172) 	at bhz.t(SourceFile) 	at bhz.az(SourceFile:1000) 	at bhz.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Now it crashes everytime I try to join with

13:04:41 | bhz | ########## GL ERROR ##########
-- | -- | --
13:04:41 | bhz | @ Pre render
13:04:41 | bhz | 1280: Invalid enum

and the other classic error on top

https://pastebin.com/QPE1VCCg the crash-reports log

EDIT: I deleted mods.json and now I can join...

**Comment by LeafHacker** [comment] 2017-08-26 14:28
Due to Impact's obfuscation the stack trace is not particularly helpful. It
looks like some mod's event listener threw a NullPointerException, but
without deobfuscating the stack trace (@ZeroMemes can ZKM do that?) there's
no way to know which.

It might help if you could let us know what mods you had enabled and what
you were doing so that we can try to reproduce the crash.

**Comment by ZeroMemes** [comment] 2017-08-26 15:56
Looks like it was caused by the "Fast Break" module

**Comment by ZeroMemes** [comment] 2017-08-26 15:57
Fixed in 4.1

**Closed by ZeroMemes** 2017-08-26 15:57 UTC
Labels: Bug
