### ISSUE TITLE
Dolphin Jesus causes jumps while typing in chat

### ISSUE THREAD

**Issue by ArthurDent69** [ImpactDevelopment/ImpactClient#551] opened 2018-04-25 05:01 UTC
I recently installed your client and enjoy it very much, with that out of the way the issue is simple. Whenever I am in chat on a server or use chat in single player every press of the space-bar causes my avatar to jump, as I use chat a great deal on servers this has led to hunger drain. I turned all mods off and still had the issue, I then went to vanilla and didn't find a problem similar, I tried 2 other client side mods and no problems with them either. I didn't see anything out of the ordinary in my logs so haven't copied them over. I asked other players on the server if they use impact but none are having the same glitch, this leads me to believe it may have something to do with Ubuntu/Linux as I am the only player running this as an OS.

 Additional Client Info
- Impact Version: 4.2 for 1.12.2
- Using Optifine?  No
- Enabled mods: **Player** : No Fall ; Movement : No Push ; **Render** : ESP' HUD, Nametags, Radar          and Tracers : **Misc** ; Anit-Hazard and Crosshair
- Operating System: Xubuntu 16.04.4 LTS

**Comment by SuperOP535** [comment] 2018-04-25 08:26
I were having this glitch in 3.x and 4.1 also (windows)

**Comment by LeafHacker** [comment] 2018-04-25 11:42
Almost sounds like inventory move. I'm using Arch but haven't noticed this. I doubt it is distro related since the GUI and in-game keyboard handling is seperate

**Comment by ArthurDent69** [comment] 2018-04-25 12:12
I do not know what Inventory Move is, is that an option in one of the mods of Impact? As I said in the report this doesn't occur at any other time, only when I have Impact active as my client. It also has not been seen by the players who recommended Impact to me on Constantium. Could you please provide more detail as to what Inventory Move is and how I might disable it. Thank you.

**Comment by LeafHacker** [comment] 2018-04-25 15:48
Movement->Inventory is an Impact mod that passes key events in GUIs like inventory to the game to allow movement while in the inventory. It wouldn't have caused this however, since it explicitly checks that the GUI isn't GuiChat or the search bar in creative mode.

**Comment by LeafHacker** [comment] 2018-04-25 15:49
Do other key events propogate? e.g. does typing W in chat move the player forward? Are any other GUIs affected? e.g. Inventory, Sign, Book, Chest, etc

**Comment by LeafHacker** [comment] 2018-05-28 18:29
Ok, managed to reproduce on the 4.2 release, but not on the latest dev version. I suspect this may be caused by the dev version running on Forge, which might not allow the player to jump while chat is open. Forge does weird stuff like that.

Either way the code looks bad, so I added some additional checks to ensure normal behaviour when a GUI is open. Should be fixed in 4.3

**Closed by LeafHacker** 2018-05-28 18:29 UTC
Labels: Bug
