### ISSUE TITLE
Freecam on a pig

### ISSUE THREAD

**Issue by Arimzon** [ImpactDevelopment/ImpactClient#934] opened 2019-02-19 03:00 UTC
Looks related to #563 but after reviewing it they arent the same

Bug was on 2b2t - unknown if server specific

I was riding a pig while using entityspeed/riding or whatever the hack is specifically called. I freecammed while on a pig, but when I exited freecam the pig started having weird teleport animations which leads me to suspect it has to do with the anticheat there but oh well. The bug also didn't allow me to load chunks that weren't loaded when I went into freecam whilst on the pig, so after I exited freecam, I had to rejoin the server in order to actually go anywhere.

I have replicated it multiple times on 2b2t. I can do it on video if absolutely necessary

Impact 4.4, Feb 18 2019

**Comment by leijurv** [comment] 2019-02-21 17:19
I can confirm this behavior when logging in / out while on a pig on 2b2t, but I'm not certain freecam is always the cause... it could just be the Riding utility module perhaps
It's also happened on a boat on 2b, and freecam was definitely the cause there. 

A video would probably help, because I know what you're talking about with the weird teleport animations but others might not =)

**Comment by ZeroMemes** [comment] 2019-02-24 19:10
Fixed in 4.5 by the Freecam rewrite

**Closed by ZeroMemes** 2019-02-24 19:10 UTC
Labels: Bug

**Comment by LeafHacker** [comment] 2019-03-01 22:46
If there's an underlying issue in Riding this may not be fixed for other cases such as the log out/in example @leijurv gave
