### ISSUE TITLE
Inventory Walk Not Working

### ISSUE THREAD

**Issue by Acedropthebase** [ImpactDevelopment/ImpactClient#1150] opened 2019-04-19 20:13 UTC
On impact 4.6 forge for 1.12.2 inventory walk is not working for when inventory or for in hoppers. I’m using world download, kami and journey mod with impact. Even with these mods removed inventory walk still seems to not work.

**Comment by leijurv** [comment] 2019-04-19 22:44
Duplicate of #1104

**Closed by leijurv** 2019-04-19 22:44 UTC
