### ISSUE TITLE
Auto Reconnect broken

### ISSUE THREAD

**Issue by mrx12335** [ImpactDevelopment/ImpactClient#492] opened 2017-12-29 03:56 UTC
### What happens?
auto reconnect doesn't delay the reconnect even when you change it in the GUI

### When does this happen?
once its broken every time when you try to reconnect and it start happening when you change the delay

### Exact steps to reproduce?
change the delay 
log into a server when it restarts
then you see ti gliches

- Impact Version: 4.1 for 1.12.2
- Using Optifine? No
- Enabled mods: Auto reconnect and others that have nothing to do with auto reconnect

- Operating System: Windows 7 64bit

**Comment by ZeroMemes** [comment] 2017-12-29 05:30
Duplicate of #468

**Closed by ZeroMemes** 2017-12-29 05:30 UTC

**Comment by mrx12335** [comment] 2017-12-29 05:47
Sorry
