### ISSUE TITLE
Repetitive problem 

### ISSUE THREAD

**Issue by Abstraction98** [ImpactDevelopment/ImpactClient#784] opened 2018-10-27 01:10 UTC
### Whats is the issue?
the issue is when i close minecraft, any color changer option that i set to rainbow mode wont stay in rainbow mode.

### What happens?
when i close minecraft the rainbow mode for any color changer option will turn off and be set to whatever color it stops on at the time of your game closing down.

### Exact steps to reproduce

- Step one: load up minecraft with the impact 4.4 for 1.12.2 client.
-Step two: turn on rainbow mode for something in storage ESP and Crosshair+.
-Note about step two: i use rainbow mode on echest or storage ESP mod and i use raindbow mode for the crosshair+ mod.
-Step three: close the game completely as if you were done playing for the day.
-Step four: reopen minecraft with the impact 4.4 for 1.12.2 client and check the color changer options 

 ### More Info 

- Impact Version: 4.4 for 1.12.2
- Using Optifine? No 
- Using LiteLoader? No
- Enabled mods: cameraclip, ESP, hud, light, main menu, nametags, storageESP, tracers, trajectories, auto armor, auto totem, auto eat, velocity, auto reconnect, crosshair+, middle click friends, weather, and no push. 
- Operating System: windows 10 pro 64 bit
</details>

**Comment by ZeroMemes** [comment] 2018-10-27 16:16
Duplicate of #766

**Closed by ZeroMemes** 2018-10-27 16:16 UTC
