### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ZeroMemes** [ImpactDevelopment/ImpactClient#489] opened 2017-12-11 20:42 UTC
A changelog should be made for each release, formatted as seen here: http://keepachangelog.com/en/1.0.0/

**Comment by SuperOP535** [comment] 2017-12-23 19:09
Duplicate of #179

**Comment by InstantReflex** [comment] 2018-01-02 00:14
oh mu dude you just got *pranked*

**Comment by ZeroMemes** [comment] 2018-05-03 19:37
Created a new file in the resources repo to hold the changelog.

https://github.com/ImpactDevelopment/Resources/blob/master/data/changelog.txt

**Closed** 2018-05-03 19:42 UTC
Labels: Enhancement

**Comment by LeafHacker** [comment] 2018-05-03 22:11
Personally I prefer having a changelog within the repo the changes happen in. That way when you make a commit you update the changelog as part of your commit.
