### ISSUE TITLE
Exception in thread "Client thread" 

### ISSUE THREAD

**Issue by davidebic** [ImpactDevelopment/ImpactClient#11] opened 2017-01-04 12:03 UTC
When i start Impact 1.11 I get this errr :Exception in thread "Client thread" 
I tried deleting shaders folder, 
and i tried pasting original assets but it didm't work.
Someone can help?

**Comment by davidebic** [comment] 2017-01-04 12:39
The Log: [12:55:05 INFO]: Minecraft Launcher 1.6.70 (through bootstrap 5) started on windows...
[12:55:05 INFO]: Current time is Jan 4, 2017 12:55:05 PM
[12:55:05 INFO]: System.getProperty('os.name') == 'Windows 10'
[12:55:05 INFO]: System.getProperty('os.version') == '10.0'
[12:55:05 INFO]: System.getProperty('os.arch') == 'amd64'
[12:55:05 INFO]: System.getProperty('java.version') == '1.8.0_91'
[12:55:05 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[12:55:05 INFO]: System.getProperty('sun.arch.data.model') == '64'
[12:55:05 INFO]: proxy == DIRECT
[12:55:06 INFO]: JFX is already initialized
[12:55:06 INFO]: Refreshing local version list...
[12:55:06 INFO]: Refreshing remote version list...
[12:55:06 INFO]: Refresh complete.
[12:55:06 INFO]: Loaded 19 profile(s); selected '1.11.1'
[12:55:06 INFO]: Refreshing auth...
[12:55:06 INFO]: Logging in with access token
[12:55:07 INFO]: Getting syncinfo for selected version
[12:55:07 INFO]: Queueing library & version downloads
[12:55:07 INFO]: Download job 'Version & Libraries' started (16 threads, 33 files)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar for job 'Version & Libraries'... (try 0)
[12:55:07 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Download job 'Resources' skipped as there are no files to download
[12:55:08 INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.24\authlib-1.5.24.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.4\realms-1.10.4.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.24\authlib-1.5.24.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Attempting to download C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11.jar for job 'Version & Libraries'... (try 0)
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209\lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.4\realms-1.10.4.jar for job 'Version & Libraries': Local file matches hash, using that
[12:55:08 INFO]: Finished downloading C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11.jar for job 'Version & Libraries': Couldn't connect to server (responded with 505) but have local file, assuming it's good
[12:55:08 INFO]: Job 'Version & Libraries' finished successfully (took 0:00:00.438)
[12:55:08 INFO]: Launching game
[12:55:08 INFO]: Unpacking natives to C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11-natives-6359989329722
[12:55:08 INFO]: Launching in C:\Users\david_000\AppData\Roaming\.minecraft
[12:55:08 INFO]: Half command: C:\Program Files\Java\jdk1.8.0_91\jre\bin\javaw.exe -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Djava.library.path=C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11-natives-6359989329722 -cp C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\netty\1.6\netty-1.6.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\1.5.24\authlib-1.5.24.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\com\mojang\realms\1.10.4\realms-1.10.4.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\7.0.12_mojang\fastutil-7.0.12_mojang.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\david_000\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11.jar net.minecraft.client.main.Main
[12:55:08 INFO]: Looking for orphaned versions to clean up...
[12:55:08 INFO]: Looking for old natives & assets to clean up...
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: java.io.IOException: Stream closed
[12:55:10 ERROR]: Game ended with bad state (exit code 1)
[12:55:10 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[12:55:10 INFO]: Deleting C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11-natives-6359989329722
[12:55:10 WARN]: Couldn't delete C:\Users\david_000\AppData\Roaming\.minecraft\versions\Impact 1.11\Impact 1.11-natives-6359989329722 - scheduling for deletion upon exit

**Comment by Purpzie** [comment] 2017-01-10 02:51
I've been having the same problem. It also says "Completely ignored arguments: [--nativeLauncherVersion, 307]" above "Exception in thread "Client thread"" on the Game Output tab in the game launcher.

**Comment by LeafHacker** [comment] 2017-01-11 01:37
This may be a duplicate of #2

**Comment by shepanator** [comment] 2017-01-18 08:40
Optifine has internal shaders that are active even when you delete the shaders folder, so you need to start minecraft without impact, turn off the internal shaders, then you should be able to start impact client normally.

**Comment by ZeroMemes** [comment] 2017-07-16 20:58
This will no longer be an issue for builds running on Client API

**Closed** 2017-08-05 17:22 UTC
Labels: fixed-unreleased
