### ISSUE TITLE
Phase and Freecam

### ISSUE THREAD

**Issue by jkid291** [ImpactDevelopment/ImpactClient#83] opened 2017-08-06 08:07 UTC
Phase does not work at all (even on singleplayer world) amd freecam does not go through blocks it acts like there is a wall there

**Comment by LeafHacker** [comment] 2017-08-06 20:13
Firstly, this issue covers multiple topics, hence marking as invalid.

Secondly this is a duplicate of #49 and #52, make sure to search for existing issues before reporting.

**Closed by LeafHacker** 2017-08-06 20:13 UTC
Labels: duplicate, invalid
