### ISSUE TITLE
adjustable speed for every speed mode (even if they don't work properly)

### ISSUE THREAD

**Issue by jefferyw08** [ImpactDevelopment/ImpactClient#195] opened 2017-09-04 06:47 UTC

**Comment by Bircko** [comment] 2017-09-04 12:40
Wie stellst du dir das bitte vor?

**Comment by VitorISs** [comment] 2017-09-04 16:30
duplicate of #103

**Comment by zPeanut** [comment] 2017-09-04 19:11
was

**Closed** 2017-09-04 19:13 UTC
Labels: Duplicate, Enhancement

**Comment by LeafHacker** [comment] 2017-09-06 08:38
@jefferyw08 please don't re-post issues you have already submitted. All this does is add yet another duplicate to filter out.

If you feel like an issue has been forgotten, you could comment on the original issue. However even this is probably unnecessary, since we routenly look through the issues to see what needs doing.

**Comment by LeafHacker** [comment] 2017-09-06 08:40
@Bircko please keep all conversation here in English. It is pointless communicating with us in a language we may not understand.
