### ISSUE TITLE
.locate is broken in multiplayer

### ISSUE THREAD

**Issue by NiceAesth** [ImpactDevelopment/ImpactClient#979] opened 2019-03-05 21:29 UTC
### What happens?
Whenever I try to use the locate command on multiplayer, it errors out that the server seed must be provided.

### Exact steps to reproduce?

- Join a multiplayer server
- Type .locate Mansion <seed> (e.g. .locate Mansion 7439324006772943016)
- Error mentioned above will appear

<details> 
  <summary><strong>Game output</strong></summary>
 
```
`[Impact] Server seed must be provided!`
```

</details>

<details> 
 <summary><strong>Additional Client Info</strong></summary>
**- Impact Version:** 4.5 for 1.12.2
<br>
**- Using Optifine?** Yes
<br>
**- Using LiteLoader?** No
<br>
**- Enabled mods:** AutoCheat, MiddleClickFriend, LevitationControl, Chams, Criticals, KillAura, NoFall, AutoTotem, AutoWeapon, AntiOverlay, LogPosition, Radar, Trajectories, StorageESP, AutoArmor, SmoothAim, AntiVanish, Jesus, Crosshair+, ItemSaver, AutoTool, AntiBlind, AutoEat, Weather, AntiAim, ESP, HitBox, Light
<br>
**- Operating System:** Windows 10 64bit
</details>

**Comment by LeafHacker** [comment] 2019-03-05 23:11
Duplicate of #94

**Closed by LeafHacker** 2019-03-05 23:11 UTC
