### ISSUE TITLE
BlockESP w/ tracers

### ISSUE THREAD

**Issue by gwsm1992** [ImpactDevelopment/ImpactClient#569] opened 2018-04-30 00:45 UTC
This is a feature I would like to see added.

On 2b2t, in a video, I saw a player wandering in the nether with something called "PortalESP" turned on. Basically, when a nether portal rendered within view, tracers would go to the nether portal blocks. 

This seems like something that would be easy to add. Its basically just tracers to certain blocks. It could be implemented as tracers to blocks that could be chosen. It could be used to find portals in the nether, but also find diamonds more easily if one didn't want to use xray, or even with xray at the same time, finding made blocks, like cobblestone, to find bases more easily, and more.

**Comment by LeafHacker** [comment] 2018-04-30 00:51
Duplicate of #241

**Closed by LeafHacker** 2018-04-30 00:51 UTC
