### ISSUE TITLE
Team Pepsi Background Does not load if screen res is too low.

### ISSUE THREAD

**Issue by TheForgottenKing** [ImpactDevelopment/ImpactClient#31] opened 2017-06-11 21:02 UTC
My res is 1024x600 and it doesn't load. I'll try resizing it later, but point remains. IDK if this is reproducable.

**Comment by LeafHacker** [comment] 2017-06-11 23:02
Can't reproduce by launching in windowed mode (850x480). This may be caused by your naughty resource repo clone, idk how though.

**Comment by TheForgottenKing** [comment] 2017-06-27 22:11
Might be because my gpu is s h i t

Also performance drops lower than it already is.

**Comment by LeafHacker** [comment] 2017-08-05 17:47
Closing due to inability to reproduce, the age of this issue and the fact that a new version is out.

If this can be reproduced in [4.0](https://impactdevelopment.github.io/#download) please add detailed instructions to reproduce and I will re-open.

**Closed by LeafHacker** 2017-08-05 17:47 UTC
Labels: bug, can't-reproduce
