### ISSUE TITLE
download is down

### ISSUE THREAD

**Issue by olilord123** [ImpactDevelopment/ImpactClient#1383] opened 2019-07-19 09:48 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'impact download'
2. Click on 'any download'
3. See error

**Expected behavior**
when i press download this shows up: "This site can’t be reached The webpage at http://evassmat.com/K4AN might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED"

**Screenshots**

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
- Using Optifine? 
- Using LiteLoader? 
- Enabled mods: 
- Operating System: 

</details>

**Additional context**

**Comment by Rindula** [comment] 2019-07-19 12:04
Duplicate of #1382? It works on my Site ...

**Closed** 2019-07-19 20:53 UTC
Labels: Bug
