### ISSUE TITLE
Typing F-keys can prevent toggling mods (inc. ClickGUI)

### ISSUE THREAD

**Issue by Adrianoo1804** [ImpactDevelopment/ImpactClient#539] opened 2018-04-22 10:13 UTC
I go onto Impact 4.2 and press rshift to enable ClickGui. It works the first time I press it, but when I exit and press it again, it does nothing. 

### Exact steps to reproduce?

1. Enter either a server or single player.
2. Click rshift to enable ClickGui.
3. Press esc or some button to leave the menu.
4. Click rshift again. It doesn't work and it does legit nothing.

**Comment by LeafHacker** [comment] 2018-04-22 13:52
I can't reproduce this, but I have just fixed a similar bug which lead to clickgui not being enabled/disabled properly. For now I'll mark this as can't reproduce.

**Comment by LeafHacker** [comment] 2018-04-25 11:50
@MastaNub that sounds different. I wonder if maybe your keybinds are unset or something

**Comment by JadonZufall** [comment] 2018-05-27 01:03
Same problem I can open it a view times but if I full screen with it open or leave it open for to long I cant re open it after closing it

**Comment by LeafHacker** [comment] 2018-05-30 23:39
I think this is caused by something related to fullscreen. Which would explain why I couldn't reproduce the issue, as I never use fullscreen mode!

**The workaround (for now) is to not use fullscreen mode, instead maximise your window**

Any further information will probably help fix this, can you guys all confirm you had used fullscreen between booting Impact and experiencing the issue? **Has anyone had this without using fullscreen?**

**Comment by LeafHacker** [comment] 2018-06-02 01:07
**Fixed in 4.3.**

This was caused by a design flaw in the implementation of #166 and made worse by a quirk of the implementation of #66.

Typing F-keys while clickGUI was open would cause them to be added to a list of "bad keys" being held. If that list isn't empty when toggling a mod, the mod will refuse to toggle. F11 would sometimes do this even if clickGUI wasn't open, hence why fullscreen was causing issues.

**Closed by LeafHacker** 2018-06-02 01:07 UTC
Labels: Bug
