### ISSUE TITLE
Client not showing up in Versions

### ISSUE THREAD

**Issue by Trance25** [ImpactDevelopment/ImpactClient#8] opened 2016-12-31 09:53 UTC
i have downloaded impact 1.11 and nothing went wrong but when i went to go start up impact the client it wasn't in versions? i have checked the .json and it's definately not down the at the bottom the available versions and it's also in the versions folder, all the names are Impact 1.11 idk whats going on :(

**Comment by LeafHacker** [comment] 2016-12-31 14:37
Impact should be installed as a directory within the versions directory that contains the jar and json.

It should look like this

```
- .minecraft
  - versions
    - 1.10
    - 1.11 
    - Impact 1.11
      - Impact 1.11.jar
      - Impact 1.11.json

It sounds to me like you have instead placed the jar and json directly in the versions directory, therefore I will close this as not being a bug. If this issue continues or I am mistaken, please comment letting us know with as much information as possible

**Comment by Trance25** [comment] 2016-12-31 14:55
I have done exactly that, however I am still unable to use the client, I downloaded a couple extra clients to see if the same problem would occur, one worked fine while the other wasn't showing up. While I am able to use the client which works fine it isn't very user friendly and I was recommended impact by a friend. Also I am typing this comment on my phone so the next time I am able to use my computer I can give you more details about the issue. All help is appreciated thanks. :)

**Comment by LeafHacker** [comment] 2016-12-31 16:49
Hm, once you've ensured it is installed correctly into the versions directory (and that it is actually unzipped) the next thing to check is whether you have setup a profile for it and looked through the versions drop down in the launcher's profile editor.

I would assume that since you have installed another client, you know how to do this, unless the other client made a new profile for you (like forge and optifine do). Impact doesn't do that. You have to make your own profile.

**Comment by Trance25** [comment] 2017-01-01 03:54
i hopped back onto my computer and when i started up the minecraft launcher i looked into the game dir, what it seems to be doing (as well as the other client that wont work) is continually removing itself from the versions folder. i have no idea why this happens but that's what i'm seeing

**Comment by LeafHacker** [comment] 2017-01-01 06:28
Very odd. Are you using the new launcher or the old one? I've not tested
the new launcher, though I've heard it has some issues (not this one).

This is almost certainly either a bug in the launcher or some kind of
virus. I can't see how impact would be able to cause this behaviour.

**Comment by shepanator** [comment] 2017-01-18 08:34
Did you rename the impact folder by any chance?
The minecraft launcher only recognises different client versions if the folder, .json file and .jar file within all have identical names, so if you renamed the 'impact 1.11' folder (while you were unzipping it for example) then the launcher won't recognise it.

**Comment by Trance25** [comment] 2017-01-20 20:22
No I didn't however I have a feeling it might be because I extracted the files once I downloaded the client, I'll download the client again this time keeping it zipped I'll see how it goes

**Comment by ZeroMemes** [comment] 2017-03-23 17:29
> (as well as the other client that wont work) is continually removing itself from the versions folder. i have no idea why this happens but that's what i'm seeing

This behavior is most likely caused by the new launcher or some kind of virus present on your computer. Due to the same results with another client it is safe to say that it isn't an issue unique to impact.

**Closed by ZeroMemes** 2017-03-23 17:29 UTC
Labels: question
