### ISSUE TITLE
Item Saver drops items instead of moving them to the inventory

### ISSUE THREAD

**Issue by MightyKnight** [ImpactDevelopment/ImpactClient#719] opened 2018-09-26 12:56 UTC
Item Saver currently drops items if their durability is 0.

Instead it should move items from the hotbar into free inventory space and only fall back to dropping if no slot is left.

**Comment by ZeroMemes** [comment] 2018-09-26 21:35
Item Saver should already be doing this. Maybe the check is faulty?

**Comment by LeafHacker** [comment] 2018-09-30 20:49
Does this only happen with a full inventory? IIRC the module doesn't have a system for swapping with populated slots.

**Comment by MightyKnight** [comment] 2018-10-01 05:04
Happens with empty inventory too. Strange

**Comment by ZeroMemes** [comment] 2018-10-16 19:43
I mean this *should* work. I'll test it myself LOL

![Item Saver Source Code](https://i.imgur.com/pldVOdL.png)

**Comment by ZeroMemes** [comment] 2018-10-16 19:46
Caused by an inverted boolean value. Fixed in 4.5

**Closed by ZeroMemes** 2018-10-16 19:46 UTC
Labels: Bug

**Comment by ZeroMemes** [comment] 2018-10-16 21:01
Will be fixed in Impact 4.4 Hotfix 4
