### ISSUE TITLE
Macros not working.

### ISSUE THREAD

**Issue by DanisDGK** [ImpactDevelopment/ImpactClient#525] opened 2018-04-18 09:24 UTC
When I click the Impact button, the Macros tab is greyed out.

**Comment by DanisDGK** [comment] 2018-04-18 09:25
Impact 4.1 1.12.2 Version

**Comment by SuperOP535** [comment] 2018-04-18 09:59
blame brady, he just put the button but did not implement anything

**Comment by LeafHacker** [comment] 2018-04-18 14:37
There isn't a Macros GUI (well, there isn't macros at all atm), hence why the button is disabled. The button is left over from when there _was_ a Macros system before Impact got rewritten for ClientAPI.

Closing this as a duplicate of #153

**Closed by LeafHacker** 2018-04-18 14:37 UTC
