### ISSUE TITLE
new ClickGUI crashes when on mac

### ISSUE THREAD

**Issue by krabbypattified** [ImpactDevelopment/ImpactClient#5] opened 2016-12-23 23:57 UTC
Right shift crashes Minecraft. Not sure what's causing it, but it only happens for this specific client.

If it matters, I'm on a Mac, and I was in single player creative mode.

**Comment by LeafHacker** [comment] 2016-12-24 05:28
this is caused by some opengl stuff in the new clickgui menu that for some unknown reason crashes on macs.

A work around is to use a different clickgui mode, like classic or para. You can use tha tabgui or the json config file to change the clickgui mode.

**Comment by oscarmartian** [comment] 2017-01-22 00:28
Where would one find the json config file? Is it just the file that appears next to the .jar, or is it somewhere else?

**Comment by ZeroMemes** [comment] 2017-07-27 00:04
Issue fixed in 4.0

**Comment by oscarmartian** [comment] 2017-07-27 08:50
Did someone say 4.0?

**Closed** 2017-08-05 17:22 UTC
Labels: bug, fixed-unreleased
