### ISSUE TITLE
FPS Limiter While Not Focused On Minecraft

### ISSUE THREAD

**Issue by FlyingBajr** [ImpactDevelopment/ImpactClient#975] opened 2019-03-03 07:22 UTC
A simple option to limit the fps of Minecraft to 5fps while the window is not focused. This will help because i often use one of my accounts auto walking/fishing/walking so that my computer wont use as much processing power. Aristois has this feature.

**Comment by SuperOP535** [comment] 2019-03-05 19:48
Duplicate of #610

**Closed by SuperOP535** 2019-03-05 19:48 UTC
