### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#473] opened 2017-11-19 20:05 UTC
Simple. Would be nice if you could save ur current keybinds, enabled hacks etc and be able to choose from a list you made.

**Comment by SuperOP535** [comment] 2017-11-24 21:43
Duplicate, #219

**Comment by ZeroMemes** [comment] 2017-11-24 21:51
Duplicate of #450

**Closed by ZeroMemes** 2017-11-24 21:51 UTC
