### ISSUE TITLE
Add Java 11 compatibility

### ISSUE THREAD

**Issue by DarkoGNU** [ImpactDevelopment/ImpactClient#982] opened 2019-03-06 19:47 UTC
### What is your suggestion?

Vanilla Minecraft, OptiFine (usually this is needed: [https://github.com/sp614x/optifine/files/2342731/NewerJavaCompatibility.zip](url)), and possibly other hacked clients - I tested only Wurst, it works out of the box... they all work fine with Java 11, the latest LTS release. Can you add Java 11 support to Impact? I don't see any advantages besides a little performance improvement, but I just like using the latest available software, so Java 11 makes me happy :smiley: 

### Why is it useful?

Java 11 is the default JRE on many Linux distros, so people who downloaded the latest Java won't have to install Java 8 just to run Impact. They also won't have to change Java executable in Impact profile (or default Java version).

**Comment by SuperOP535** [comment] 2019-03-06 20:28
You should be able to add the NewerJavaComp thing manually

**Comment by LeafHacker** [comment] 2019-03-07 00:06
This isn't (just?) an Impact issue, this is an upstream issue in legacylauncher/launchwrapper. This is one of the main reasons cpw is replacing launchwrapper with modlauncher going forward. The 1.13 version of Impact will likely use modlauncher and this should be resolved.

Best practice on linux is to configure JRE=8 as a dependancy of Minecraft to ensure mods & old versions using lanuchwrapper run correctly, see [discussion on the AUR](https://aur.archlinux.org/packages/minecraft-launcher) for example. There's no reason why JRE 8 can't exist along side other versions either, and it doesn't have to be the default for other programs either - just minecraft.

**Comment by ZeroMemes** [comment] 2019-03-07 02:09
This is a Minecraft issue lmao

**Comment by 0-x-2-2** [comment] 2019-03-07 19:45
The same thing you used with optifine should also work with impact.

**Comment by DarkoGNU** [comment] 2019-03-11 15:35
Well... Impact with Java 11 doesn't work for me, even though OptiFine works
https://paste.ee/p/Zko1x

**Comment by 0-x-2-2** [comment] 2019-03-11 15:41
lol upstream issue again

**Comment by ZeroMemes** [comment] 2019-03-18 03:25
**Won't Fix**: This issue is caused by [Mixin](https://github.com/SpongePowered/Mixin). The appropriate place to address the issue would be on that repository.

**Closed by ZeroMemes** 2019-03-18 03:25 UTC
Labels: Bug, Upstream
