### ISSUE TITLE
Crosshair+ renders at the top left of the screen, not the center, in 4.4

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactClient#748] opened 2018-10-12 02:26 UTC
Broken since 4.3 😠

**Comment by leijurv** [comment] 2018-10-13 05:38
Yo this only happens with optifine sorry @ZeroMemes

**Comment by ZeroMemes** [comment] 2018-10-13 23:18
Related to #743

**Comment by ZeroMemes** [comment] 2018-10-13 23:37
Caused by the Anti Alias shader that Optifine applies in the ``EntityRenderer#updateCameraAndRender(float, long)`` method. Crosshair+ now uses [RenderScreenEvent](https://github.com/ImpactDevelopment/ClientAPI/blob/1.12.2/src/main/java/clientapi/load/mixin/MixinEntityRenderer.java#L53) in 4.4, and both ESP and Nametags have used it for a while. I have an idea to fix this.

**Comment by leijurv** [comment] 2018-10-14 17:46
brady did this *dab*

**Comment by leijurv** [comment] 2018-10-14 17:47
prankt this is not really fixed there were opengl errors in chat every 10 seconds or so

**Comment by ZeroMemes** [comment] 2018-10-15 03:05
Fixed by https://github.com/ImpactDevelopment/ClientAPI/commit/e85ca871808932ad14979e12de7ccd8681c5cfbf

**Closed by ZeroMemes** 2018-10-15 03:05 UTC
Labels: Bug
