### ISSUE TITLE
Waypoints

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#1080] opened 2019-04-05 06:44 UTC
Simple, just a module which lets you add or remove waypoints, (((maybe?))) baritone integration, and show tracers to the goal.

**Comment by uwuplant** [comment] 2019-04-05 20:38
(this might not be what you mean)

Baritone can already do that with the command `save`.

**Comment by EvilSourcerer** [comment] 2019-04-05 20:39
no it needs to have tracers 🦍

**Comment by uwuplant** [comment] 2019-04-05 20:40
a

**Comment by TotallyNotLeet** [comment] 2019-04-06 18:49
+1

**Comment by LeafHacker** [comment] 2019-04-08 20:38
Duplicate of #203

**Closed** 2019-04-08 21:10 UTC
Labels: Duplicate
