### ISSUE TITLE
Impact GUI not opening

### ISSUE THREAD

**Issue by Eric-on-2b2t** [ImpactDevelopment/ImpactClient#641] opened 2018-07-10 21:44 UTC
### What happens?

I am using impact 4.2 and running minecraft 1.12.2. The client works normally until all of a sudden, everything seems locked into place. When I press any of the keys that were binded to modules, nothing happens. Also I cannot bring up the GUI even if I press RSHIFT.
### Exact steps to reproduce?

- Open up a new world. The game window should be fullscreen
- Press RSHIFT. The GUI appears.
- Now press F11 to bring the game out of fullscreen
- Press ESC to hide the GUI. now the bug occurs and every module seems to be 'frozen'
- This is not the only way to trigger the bug, and the bug can be quite unpredictable sometimes. Also, even after closing and reopening the world, the bug persists, and I must restart minecraft entirely to be able to 'unfreeze' the modules.

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
The game did not crash so there is not a crash report
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.2 for 1.12.2
- Using Optifine?  No
- Enabled mods:  AntiHunger effective, ESP shader, Nametags, Inventory, NoSlow, Tracers, Light
- Operating System:  Windows 10, 64 bit

</details>

**Comment by Eric-on-2b2t** [comment] 2018-07-10 21:46
This does not seem to happen on impact 4.1, which is why I am using 4.1 at the moment.

**Comment by LordQuadrato** [comment] 2018-07-10 21:47
Duplicate of #539

**Closed by LordQuadrato** 2018-07-10 21:47 UTC

**Comment by LeafHacker** [comment] 2018-07-10 22:08
Even though this is a duplicate, I'm impressed by the clear, concise and useful information included.

This definitely would have made it easier to fix if this had been the original report, well done!
