### ISSUE TITLE
Crosshair+ is missing half the crosshair 

### ISSUE THREAD

**Issue by TFall** [ImpactDevelopment/ImpactClient#57] opened 2017-08-05 19:30 UTC
![screenshot_34](https://user-images.githubusercontent.com/24363160/28998192-5b5acad0-79fb-11e7-889e-392a50733c92.png)

**Comment by LeafHacker** [comment] 2017-08-05 19:39
Duplicate of #44

**Closed by LeafHacker** 2017-08-05 19:39 UTC
Labels: duplicate
