### ISSUE TITLE
Freecam: Accept ALL server movement packets

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#821] opened 2018-10-28 08:08 UTC
While in Freecam, your actual body should still be able to move from gravity/knockback/explosions/water/etc. 

It looks super suspicious for a player to suddenly start taking no knockback because they're freecaming a base. 

Pretty sure a certain smoking mod has this.

~~[Would be really awesome to be able to freecam around while Baritone is navigating.][681]~~

[681]: https://github.com/ImpactDevelopment/ImpactClient/issues/681

**Comment by MightyKnight** [comment] 2018-10-28 12:28
Relates to #681

**Comment by LeafHacker** [comment] 2018-10-28 12:43
Serverside movement should be accepted (and visible on the avatar), however I was pretty lazy and only handles the main movement packet, not others like explosions and velocity. Therefore this is a bug.

The idea of baritone continuing to work while in freecam is a much bigger (separate) issue which should be tracked under #681, not here.

**Comment by leijurv** [comment] 2019-02-20 03:06
Pretty much a duplicate of #912

**Closed by leijurv** 2019-02-20 03:06 UTC
Labels: Bug

**Comment by SylveonBottle** [comment] 2019-02-20 16:54
> Pretty much a duplicate of #912

This issue has a lower id number.
Doesn't that mean 912 is a duplicate of this one?

**Comment by leijurv** [comment] 2019-02-21 02:51
generally you close the one with less information, but point taken lol
