### ISSUE TITLE
Crash - Exception in "Client" thread

### ISSUE THREAD

**Issue by iTeoYT** [ImpactDevelopment/ImpactClient#27] opened 2017-05-24 11:28 UTC
Impact crashes with `Exception in thread "Client thread"`

The client is contently crashing. I do not know what to do. Any help would be appreciated!

[Launcher Log](https://pastebin.com/sCu4zrCe)

**Comment by LeafHacker** [comment] 2017-05-25 05:44
Thank you for taking the time to report this crash. Unfortunately there isn't currently enough information in the launcher log to identify the specific bug.

Providing the crash report may help, however this issue is probably already fixed by the version of impact currently in development (4.0 is a complete re-write).

This also may be one of the issues with the [New minecraft launcher](https://minecraft.net/en-us/download/alternative). Many people have had crashes when running custom clients through the new launcher, trying the [old launcher](https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.exe) may work better for you.

Closing this issue for now, since it is likely fixed in the next version and may be a duplicate of other new-launcher issues.

**Closed by LeafHacker** 2017-05-25 05:44 UTC
Labels: bug
