### ISSUE TITLE
let us be able to translate the client to other language by ourselves

### ISSUE THREAD

**Issue by lupohan44** [ImpactDevelopment/ImpactClient#1504] opened 2019-08-07 07:31 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
let us be able to translate the client to other language by ourselves.Like server plugins,it always has a language file,so we can translate it to other language by ourselves.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by mrphax0r** [comment] 2019-08-08 17:02
As suggested my me

**Comment by StijnSimons** [comment] 2019-08-08 17:03
Duplicate of #508

**Closed by StijnSimons** 2019-08-08 17:03 UTC
Labels: Suggestion
