### ISSUE TITLE
Impact 1.12.2 identifies itself as 1.12.1

### ISSUE THREAD

**Issue by mariovous** [ImpactDevelopment/ImpactClient#439] opened 2017-10-25 17:22 UTC
When i try to logon to a 1.12.2 only server with my 1.12.2 client, it says i have the wrong version. 

### What happens?
Game says its version 1.12.1, when its not.

- Impact Version: 4.1 for 1.12.2
- Using Optifine? No
- Enabled mods: Doesnt matter
- Operating System: Windows 10 64bit

**Comment by MRCROCK85** [comment] 2017-10-25 18:01
I am having this exact same issue.  I re-downloaded the appropriate files and created a new profile in the launcher, and the issue persists.

**Comment by SuperOP535** [comment] 2017-10-25 19:59
Same issue

**Comment by SuperOP535** [comment] 2017-10-25 20:01
This is a new issue, if you check the start screen it says 1.12.1.. it must be an issue with the maven stuff or json autochanged I guess? It didn't happen earlier

**Comment by ZeroMemes** [comment] 2017-10-25 20:28
I've updated the download link, there was a minor error with the JSON, although it seems odd that the error would have an effect out of nowhere. Please verify whether or not the issue is resolved.

**Comment by MRCROCK85** [comment] 2017-10-25 22:30
Replaced the JSON with the new version and all is normal now.  Thank you!

**Comment by ZeroMemes** [comment] 2017-10-26 03:43
Issue appears to be resolved, closing.

**Closed by ZeroMemes** 2017-10-26 03:43 UTC
Labels: Bug, Critical
