### ISSUE TITLE
0.2 similiar Friends Manager

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#171] opened 2017-08-27 16:47 UTC
just add one for the love of god

![screenshot_5](https://user-images.githubusercontent.com/25800857/29752105-1b88ae22-8b58-11e7-9adc-0c8a05d15dbd.png)

**Comment by LeafHacker** [comment] 2017-08-27 16:48
duplicate of #152

**Closed by LeafHacker** 2017-08-27 16:48 UTC
Labels: Enhancement
