### ISSUE TITLE
0.2 similiar Xray Manager

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#173] opened 2017-08-27 16:47 UTC
same thing
![screenshot_1](https://user-images.githubusercontent.com/25800857/29752109-302828d0-8b58-11e7-8bcd-62b5ee0511f8.png)

**Comment by SuperOP535** [comment] 2017-08-27 17:14
pls add it with block preview

**Comment by LeafHacker** [comment] 2017-08-27 17:28
Duplicate of #151

**Closed by LeafHacker** 2017-08-27 17:28 UTC
Labels: Enhancement
