### ISSUE TITLE
Nethercoords show up incorrectly in the overworld

### ISSUE THREAD

**Issue by olibols** [ImpactDevelopment/ImpactClient#58] opened 2017-08-05 19:39 UTC
That is while I am in the overworld at the top coords. No coords are related to the bottom ones.

![](http://i.imgur.com/WwF6QOm.png)

---

Edits by @LeafHacker for clarity:

- Neather coords show up while not in the neather
- The extra coords are still `coords * 8`, so not useful even if intended.

**Comment by ZeroMemes** [comment] 2017-08-05 19:51
This was intended, but reversed. The overworld should divide by 8 and the nether should multiply. Fixed in 4.1.

**Comment by LeafHacker** [comment] 2017-08-05 20:22
Might be worth having them show in the Overworld be a separate option, and make sure they don't appear in the End.

I think most people only care about the Neather/Overworld conversion while travelling in the Neather.

Perhaps

- [ ]: Coords
- [ ]: Overworld coords in the Neather
- [ ]: Neather coords in the Overworld

**Closed** 2017-08-12 05:05 UTC
Labels: bug, fixed-unreleased
