### ISSUE TITLE
Random Width and Random Height set to 0 causes a crash with SmoothAim

### ISSUE THREAD

**Issue by Boe6Eod7Nty** [ImpactDevelopment/ImpactClient#41] opened 2017-08-05 17:15 UTC
If Random Width and Random Height are set to 0, and you go within range of a mob/player or whatever is set to trigger for SmoothAim, it will crash the client.

**Comment by ZeroMemes** [comment] 2017-08-05 17:30
Caused by dividing by 0. Fixed in 4.1

**Closed** 2017-08-12 05:05 UTC
Labels: bug, fixed-unreleased
