### ISSUE TITLE
Crash happens for unknown reason when breaking blocks

### ISSUE THREAD

**Issue by Husky2490** [ImpactDevelopment/ImpactClient#721] opened 2018-09-26 21:26 UTC
### What happens?
Ever since today (I just got my WiFi adapter working on Linux), my game crashes whenever I try to break a block. The broken block is in item form when I reconnect to the server.

### Exact steps to reproduce?

- Do some kind of voodoo
- Connect to server and break a block

<details> 
  <summary><strong>Game output</strong></summary>
 

```
[16:02:58] [main/INFO]: Loading tweak class name clientapi.load.ClientTweaker
[16:02:58] [main/INFO]: Using primary tweak class name clientapi.load.ClientTweaker
[16:02:58] [main/INFO]: Calling tweak class clientapi.load.ClientTweaker
[16:02:58] [main/INFO]: Injecting into ClassLoader
[16:02:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/home/ruben/.minecraft/libraries/org/spongepowered/mixin/0.7.8-SNAPSHOT/mixin-0.7.8-SNAPSHOT.jar Service=LaunchWrapper Env=UNKNOWN
[16:02:58] [main/INFO]: FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[16:02:58] [main/INFO]: Initialized Mixin bootstrap
[16:02:58] [main/INFO]: Compatibility level set to JAVA_8
[16:02:58] [main/ERROR]: Mixin config mixins.capi.json does not specify "minVersion" property
[16:02:58] [main/INFO]: Loaded ClientAPI mixin configuration
[16:02:58] [main/ERROR]: Mixin config mixins.client.json does not specify "minVersion" property
[16:02:58] [main/INFO]: Loaded Client mixin configuration
[16:02:58] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:02:58] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[16:02:58] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:02:59] [main/INFO]: Setting user: husky2490
[16:03:00] [main/WARN]: Skipping bad option: lastServer:
[16:03:00] [main/INFO]: LWJGL Version: 2.9.4
[16:03:01] [main/INFO]: Reloading ResourceManager: Default
[16:03:01] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:03:01] [Thread-3/INFO]: Initializing LWJGL OpenAL
[16:03:01] [Thread-3/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:03:01] [Thread-3/INFO]: OpenAL initialized.
[16:03:01] [Sound Library Loader/INFO]: Sound engine started
[16:03:02] [main/INFO]: Created: 1024x512 textures-atlas
[16:03:02] [main/INFO]: Narrator library successfully loaded
[16:03:04] [main/INFO]: Loading Fonts
[16:03:04] [main/INFO]: Checking for Updates
[16:03:04] [main/INFO]: Loading Users
[16:03:05] [main/INFO]: Initialized 108 mods!
[16:03:05] [main/FATAL]: Unable to load spam config file: Spam config file is in invalid format
[16:03:05] [main/ERROR]: ########## GL ERROR ##########
[16:03:05] [main/ERROR]: @ Pre render
[16:03:05] [main/ERROR]: 1282: Invalid operation
[16:03:10] [main/INFO]: Connecting to 2b2t.org, 25565
[16:03:10] [main/INFO]: [CHAT] 2b2t is full
[16:03:13] [main/INFO]: Connecting to 2b2t.org, 25565
[16:03:15] [main/INFO]: Connecting to 2b2t.org, 25565
[16:03:27] [main/INFO]: Connecting to 2b2t.org, 25565
[16:03:28] [main/INFO]: [CHAT] 2b2t is full
[16:03:28] [main/INFO]: Loaded 15 advancements
[16:03:28] [main/INFO]: [CHAT] Position in queue: 27
[16:03:38] [main/INFO]: [CHAT] Position in queue: 26
[16:03:48] [main/INFO]: [CHAT] Position in queue: 26
[16:03:58] [main/INFO]: [CHAT] Position in queue: 26
[16:04:08] [main/INFO]: [CHAT] Position in queue: 26
[16:04:18] [main/INFO]: [CHAT] Position in queue: 25
[16:04:28] [main/INFO]: [CHAT] Position in queue: 24
[16:04:38] [main/INFO]: [CHAT] Position in queue: 23
[16:04:49] [main/INFO]: [CHAT] Position in queue: 23
[16:04:58] [main/INFO]: [CHAT] Position in queue: 23
[16:05:08] [main/INFO]: [CHAT] Position in queue: 23
[16:05:19] [main/INFO]: [CHAT] Position in queue: 22
[16:05:28] [main/INFO]: [CHAT] Position in queue: 22
[16:05:38] [main/INFO]: [CHAT] Position in queue: 22
[16:05:49] [main/INFO]: [CHAT] Position in queue: 22
[16:05:58] [main/INFO]: [CHAT] Position in queue: 22
[16:06:08] [main/INFO]: [CHAT] Position in queue: 21
[16:06:19] [main/INFO]: [CHAT] Position in queue: 21
[16:06:28] [main/INFO]: [CHAT] Position in queue: 20
[16:06:38] [main/INFO]: [CHAT] Position in queue: 20
[16:06:49] [main/INFO]: [CHAT] Position in queue: 20
[16:06:58] [main/INFO]: [CHAT] Position in queue: 19
[16:07:08] [main/INFO]: [CHAT] Position in queue: 19
[16:07:19] [main/INFO]: [CHAT] Position in queue: 17
[16:07:28] [main/INFO]: [CHAT] Position in queue: 15
[16:07:38] [main/INFO]: [CHAT] Position in queue: 14
[16:07:52] [main/INFO]: [CHAT] Position in queue: 14
[16:07:58] [main/INFO]: [CHAT] Position in queue: 14
[16:08:08] [main/INFO]: [CHAT] Position in queue: 13
[16:08:19] [main/INFO]: [CHAT] Position in queue: 13
[16:08:28] [main/INFO]: [CHAT] Position in queue: 12
[16:08:38] [main/INFO]: [CHAT] Position in queue: 10
[16:08:49] [main/INFO]: [CHAT] Position in queue: 10
[16:08:58] [main/INFO]: [CHAT] Position in queue: 10
[16:09:08] [main/INFO]: [CHAT] Position in queue: 10
[16:09:19] [main/INFO]: [CHAT] Position in queue: 10
[16:09:28] [main/INFO]: [CHAT] Position in queue: 10
[16:09:38] [main/INFO]: [CHAT] Position in queue: 10
[16:09:49] [main/INFO]: [CHAT] Position in queue: 10
[16:09:58] [main/INFO]: [CHAT] Position in queue: 10
[16:10:08] [main/INFO]: [CHAT] Position in queue: 9
[16:10:19] [main/INFO]: [CHAT] Position in queue: 8
[16:10:28] [main/INFO]: [CHAT] Position in queue: 8
[16:10:38] [main/INFO]: [CHAT] Position in queue: 8
[16:10:50] [main/INFO]: [CHAT] Position in queue: 8
[16:10:58] [main/INFO]: [CHAT] Position in queue: 8
[16:11:08] [main/INFO]: [CHAT] Position in queue: 8
[16:11:19] [main/INFO]: [CHAT] Position in queue: 7
[16:11:28] [main/INFO]: [CHAT] Position in queue: 7
[16:11:38] [main/INFO]: [CHAT] Position in queue: 7
[16:11:49] [main/INFO]: [CHAT] Position in queue: 7
[16:11:58] [main/INFO]: [CHAT] Position in queue: 7
[16:12:08] [main/INFO]: [CHAT] Position in queue: 6
[16:12:19] [main/INFO]: [CHAT] Position in queue: 5
[16:12:28] [main/INFO]: [CHAT] Position in queue: 4
[16:12:38] [main/INFO]: [CHAT] Position in queue: 2
[16:12:49] [main/INFO]: [CHAT] Position in queue: 1
[16:12:58] [main/INFO]: [CHAT] Position in queue: 1
[16:13:08] [main/INFO]: [CHAT] Connecting to the server...
[16:13:10] [main/INFO]: Loaded 259 advancements
[16:13:11] [main/FATAL]: Reported exception thrown!
f: Ticking entity
	at amu.k(SourceFile:1389) ~[amu.class:?]
	at bib.t(SourceFile:1691) ~[bib.class:?]
	at bib.az(SourceFile:1000) ~[bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at me.zero.clarinet.d5.lambda$newSlotSwapper$0(d5.java) ~[d5.class:?]
	at clientapi.util.interfaces.impl.MergedMutable.accept(MergedMutable.java:49) ~[MergedMutable.class:?]
	at clientapi.util.interfaces.impl.MutableSwapper.reset(MutableSwapper.java:68) ~[MutableSwapper.class:?]
	at me.zero.clarinet.dL.t(dL.java) ~[dL.class:?]
	at me.zero.clarinet.dj.lambda$new$2(dj.java) ~[dj.class:?]
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93) ~[Listener.class:?]
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91) ~[EventManager.class:?]
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) ~[?:1.8.0_181]
	at me.zero.alpine.EventManager.post(EventManager.java:91) ~[EventManager.class:?]
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44) ~[ClientAPIEventManager.class:?]
	at bud.handler$onPostUpdate$zzd000(SourceFile:1220) ~[bud.class:?]
	at bud.B_(SourceFile:208) ~[bud.class:?]
	at amu.a(SourceFile:1524) ~[amu.class:?]
	at amu.h(SourceFile:1500) ~[amu.class:?]
	at amu.k(SourceFile:1382) ~[amu.class:?]
	... 10 more
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 9/26/18 4:13 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at me.zero.clarinet.d5.lambda$newSlotSwapper$0(d5.java)
	at clientapi.util.interfaces.impl.MergedMutable.accept(MergedMutable.java:49)
	at clientapi.util.interfaces.impl.MutableSwapper.reset(MutableSwapper.java:68)
	at me.zero.clarinet.dL.t(dL.java)
	at me.zero.clarinet.dj.lambda$new$2(dj.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bud.handler$onPostUpdate$zzd000(SourceFile:1220)
	at bud.B_(SourceFile:208)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)
	at amu.k(SourceFile:1382)
	at bib.t(SourceFile:1691)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zero.clarinet.d5.lambda$newSlotSwapper$0(d5.java)
	at clientapi.util.interfaces.impl.MergedMutable.accept(MergedMutable.java:49)
	at clientapi.util.interfaces.impl.MutableSwapper.reset(MutableSwapper.java:68)
	at me.zero.clarinet.dL.t(dL.java)
	at me.zero.clarinet.dj.lambda$new$2(dj.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bud.handler$onPostUpdate$zzd000(SourceFile:1220)
	at bud.B_(SourceFile:208)
	at amu.a(SourceFile:1524)
	at amu.h(SourceFile:1500)

-- Entity being ticked --
Details:
	Entity Type: null (bud)
	Entity ID: 5065
	Entity Name: husky2490
	Entity's Exact location: 553153.88, 68.00, -101545.82
	Entity's Block location: World: (553153,68,-101546), Chunk: (at 1,4,6 in 34572,-6347; contains blocks 553152,0,-101552 to 553167,255,-101537), Region: (1080,-199; contains chunks 34560,-6368 to 34591,-6337, blocks 552960,0,-101888 to 553471,255,-101377)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at amu.k(SourceFile:1382)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bud['husky2490'/5065, l='MpServer', x=553153.88, y=68.00, z=-101545.82]]
	Chunk stats: MultiplayerChunkCache: 79, 79
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 25427 game time, 1365976221 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 30 total; [bud['husky2490'/5065, l='MpServer', x=553153.88, y=68.00, z=-101545.82], acs['Creeper'/12066614, l='MpServer', x=553186.50, y=68.00, z=-101576.50], acs['Creeper'/12066600, l='MpServer', x=553185.50, y=27.00, z=-101523.50], aag['Sheep'/12066604, l='MpServer', x=553171.53, y=69.00, z=-101515.81], acs['Creeper'/12066592, l='MpServer', x=553186.50, y=70.00, z=-101538.50], adk['Skeleton'/12066593, l='MpServer', x=553151.28, y=67.00, z=-101519.61], acs['Creeper'/12066594, l='MpServer', x=553169.50, y=41.00, z=-101576.50], adt['Zombie'/12066595, l='MpServer', x=553180.50, y=47.00, z=-101572.50], adn['Spider'/12066584, l='MpServer', x=553180.50, y=69.00, z=-101556.50], acs['Creeper'/12066585, l='MpServer', x=553183.50, y=27.00, z=-101522.50], adn['Spider'/12066586, l='MpServer', x=553174.50, y=52.00, z=-101534.50], adt['Zombie'/12066587, l='MpServer', x=553173.50, y=51.00, z=-101520.50], aag['Sheep'/12066588, l='MpServer', x=553181.22, y=70.00, z=-101527.21], aag['Sheep'/12066589, l='MpServer', x=553168.89, y=69.00, z=-101524.47], acs['Creeper'/12066576, l='MpServer', x=553152.51, y=68.00, z=-101525.20], zx['Cow'/12066577, l='MpServer', x=553157.84, y=69.00, z=-101535.07], zx['Cow'/12066578, l='MpServer', x=553155.06, y=69.00, z=-101535.59], zx['Cow'/12066579, l='MpServer', x=553156.83, y=69.00, z=-101535.75], acs['Creeper'/12066580, l='MpServer', x=553179.50, y=52.00, z=-101541.50], aaq['Horse'/12066581, l='MpServer', x=553163.01, y=69.00, z=-101554.94], aaq['Horse'/12066583, l='MpServer', x=553168.18, y=69.00, z=-101565.11], zx['Cow'/12066568, l='MpServer', x=553152.07, y=69.00, z=-101537.93], zx['Cow'/12066569, l='MpServer', x=553153.18, y=69.00, z=-101536.98], zx['Cow'/12066570, l='MpServer', x=553155.97, y=69.00, z=-101537.62], zx['Cow'/12066571, l='MpServer', x=553152.07, y=69.00, z=-101536.87], zx['Cow'/12066572, l='MpServer', x=553154.12, y=69.00, z=-101536.03], zx['Cow'/12066575, l='MpServer', x=553152.76, y=69.00, z=-101535.87], zx['Cow'/12066565, l='MpServer', x=553152.77, y=69.00, z=-101540.50], zx['Cow'/12066566, l='MpServer', x=553154.89, y=69.00, z=-101537.39], zx['Cow'/12066567, l='MpServer', x=553156.06, y=69.00, z=-101538.72]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.12-SNAPSHOT:4330d86:184) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:428)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-34-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 228104656 bytes (217 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	Launched Version: 1.12.2-Impact_4.3
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.3 for 1.12.2
- Using Optifine? No
- Enabled mods: Middle Click Friend, Auto Cheat AAC, Anti Hunger Smart, RainbowEnchant, Auto Reconnect, Criticals Packet, Kill Aura Multi, Auto Weapon, Auto Totem 0, Anti Hazard, ESP Shader, Storage ESP, Auto Armor, Animations, Nametags, Anti Blind, Auto Tool, Auto Eat, Weather, Tracers, Signs, Light
- Operating System: Kubuntu 18.04

</details>

**Comment by ZeroMemes** [comment] 2018-09-26 21:30
Duplicate of #653

**Closed by ZeroMemes** 2018-09-26 21:30 UTC
