### ISSUE TITLE
Cape Problem..?

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#448] opened 2017-10-29 11:17 UTC
![hlnwhdl](https://user-images.githubusercontent.com/25800857/32142983-06507784-bca3-11e7-805a-ec1ff524e6e8.png)

the support cape does still not show. is this a client side or a hacked client bug?

**Comment by VitorISs** [comment] 2017-10-29 15:18
is this duplicate of #98 ? :v

**Comment by ZeroMemes** [comment] 2017-10-29 15:22
Duplicate, closing. Will look more into original.

**Closed by ZeroMemes** 2017-10-29 15:22 UTC
Labels: Bug, Duplicate
