### ISSUE TITLE
Xray issues

### ISSUE THREAD

**Issue by dasher865** [ImpactDevelopment/ImpactClient#243] opened 2017-09-16 18:13 UTC
I can't see much of anything when I use xray

### What happens?
everything a few blocks away from me is too dark to see

### When does this happen?
Anytime I use xray to search for something

### Exact steps to reproduce?

Go underground
enable xray
try and see ores

- Impact Version:4.1 for 1.12.1
- Using Optifine?No
- Enabled mods: xray
- Operating System: Windows 10

**Comment by hugohindi** [comment] 2017-09-16 18:29
Holy shit someone actually followed the bug layout, anyways try enabling fullbright and see if that works.

**Comment by SuperOP535** [comment] 2017-09-18 16:50
Duplicate of #186

**Comment by SuperOP535** [comment] 2017-09-18 16:52
Please use the search function

**Closed** 2017-09-19 19:34 UTC
Labels: Bug
