### ISSUE TITLE
Capes

### ISSUE THREAD

**Issue by usereewrjrjeejr** [ImpactDevelopment/ImpactClient#1174] opened 2019-04-26 22:33 UTC
Fix support capes

**Comment by MastaNub** [comment] 2019-04-26 22:34
what is the issue

**Comment by usereewrjrjeejr** [comment] 2019-04-26 22:35
iirc only the left half renders

**Comment by ScanmanTM** [comment] 2019-04-27 14:28
This is a dupe of #1106

**Closed** 2019-04-27 15:20 UTC
Labels: Duplicate

**Comment by ViniDalvino** [comment] 2019-05-23 20:50
there should be a option to decide to choose the premium or support cape
