### ISSUE TITLE
Glitch: water becomes deadly after flying

### ISSUE THREAD

**Issue by ZafotheNinja** [ImpactDevelopment/ImpactClient#242] opened 2017-09-15 16:09 UTC
### What happens?
Player hurt/killed instantly upon touching water.

### When does this happen?
Upon touching water with flight disabled.

### Exact steps to reproduce?

- enable flight and fly up a few blocks 
- disable flight
- walk to water and touch it (Must be source block/still)

### Game output?
"You died" \<playername> "fell from a high place"

- Impact Version: 4.1 && 4.0
- Using Optifine? OF version but not enabled?
- Enabled mods: None, but seems like nofall packet interference. (Doesnt die when hitting ground.)
- Operating System: Windows 7 64 bit Ultimate

**Comment by ZeroMemes** [comment] 2017-09-17 22:56
Unable to reproduce with provided conditions. Are you sure you had no other mods on other than flight?

**Comment by ZafotheNinja** [comment] 2017-09-18 00:19
https://www.youtube.com/watch?v=M5uEHewAi_4&feature=youtu.be

Everything is off except flight for a moment.

**Comment by LeafHacker** [comment] 2018-07-07 08:33
This may be caused by a specific server's anticheat setup - it sounds identical to the AntiHunger/NoFall glitchiness that happens on a lot of servers.

It sounds highly likely that even if we can reproduce this somehow, it won't be possible to fix. I'm going to close this for now based on that assumption.

**Closed by LeafHacker** 2018-07-07 08:33 UTC
Labels: Can't Reproduce, Need more info

**Comment by Cerbiac** [comment] 2019-06-09 18:22
Note: `Anti-Hunger [Effective]` "Flys" instead of jumps, and is effected by this bug.
While this is old, it is common, IDK why it is "Need more info", kek.
