### ISSUE TITLE
"Non [a-z0-9/._-] character in path of location" crash when using .xray add|del

### ISSUE THREAD

**Issue by Synthestra** [ImpactDevelopment/ImpactClient#1052] opened 2019-04-02 00:03 UTC
### What happens?
Crash when entering non [a-z0-9/._-] character in .xray add|del

### Exact steps to reproduce?

- open chat
- type .xray add #
- enter
- bye bye

<details> 
  <summary><strong>Game output</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// You're mean.

Time: 02/04/19 00:55
Description: keyPressed event handler

i: Non [a-z0-9/._-] character in path of location: minecraft:#lava
	at pc.<init>(SourceFile:38)
	at pc.<init>(SourceFile:43)
	at clientapi.bw.a(bw.java:1)
	at clientapi.bw.a(bw.java:4)
	at clientapi.Y.a(Y.java:19)
	at clientapi.o.a(o.java:18)
	at clientapi.L$$Lambda$2491/1014734563.a(Unknown Source)
	at clientapi.O.a(O.java:17)
	at clientapi.t.lambda$new$1(t.java:16)
	at clientapi.t$$Lambda$2507/67053132.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1089/1227603646.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.a3.post(a3.java:4)
	at ctj.redirect$sendChatPacket$zzd000(SourceFile:1261)
	at ctj.f(SourceFile:320)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$2793/1432142010.run(Unknown Source)
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/523938160.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at cgd.a(SourceFile:309)
	at cft.c(SourceFile:875)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pc.<init>(SourceFile:38)
	at pc.<init>(SourceFile:43)
	at clientapi.bw.a(bw.java:1)
	at clientapi.bw.a(bw.java:4)
	at clientapi.Y.a(Y.java:19)
	at clientapi.o.a(o.java:18)
	at clientapi.L$$Lambda$2491/1014734563.a(Unknown Source)
	at clientapi.O.a(O.java:17)
	at clientapi.t.lambda$new$1(t.java:16)
	at clientapi.t$$Lambda$2507/67053132.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at me.zero.alpine.bus.EventManager$$Lambda$1089/1227603646.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.a3.post(a3.java:4)
	at ctj.redirect$sendChatPacket$zzd000(SourceFile:1261)
	at ctj.f(SourceFile:320)
	at ckd.b(SourceFile:301)
	at ckd.e(SourceFile:294)
	at cjg.keyPressed(SourceFile:131)
	at cfq.a(SourceFile:389)
	at cfq$$Lambda$2793/1432142010.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: cjg
Stacktrace:
	at ckd.a(SourceFile:430)
	at cfq.a(SourceFile:387)
	at cfq$$Lambda$853/523938160.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [ctj['Synthestra'/1264321, l='MpServer', x=-1651.08, y=12.00, z=-2310.70]]
	Chunk stats: MultiplayerChunkCache: 60, 60
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (208,71,-208), Chunk: (at 0,4,0 in 13,-13; contains blocks 208,0,-208 to 223,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 109669 game time, 109669 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [ctj['Synthestra'/1264321, l='MpServer', x=-1651.08, y=12.00, z=-2310.70], amm['Dirt'/1324053, l='MpServer', x=-1659.35, y=65.00, z=-2294.13], apj['Boat'/1325462, l='MpServer', x=-1657.17, y=62.52, z=-2323.61], amm['Gravel'/1429040, l='MpServer', x=-1657.88, y=11.00, z=-2303.61], amm['Flint'/1429121, l='MpServer', x=-1657.88, y=11.00, z=-2303.74], apl['Minecart with Chest'/1324973, l='MpServer', x=-1653.50, y=39.06, z=-2320.49]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.13-SNAPSHOT:52bc4fe:273) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(SourceFile:418)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:403)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 702916888 bytes (670 MB) / 2080374784 bytes (1984 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx4096m
	Launched Version: 1.13.2-Impact_4.6-beta
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6-beta
- Using Optifine? No
- Using LiteLoader? No
- Enabled mods: Irrelevant
- Operating System:Windows 10 64bit

</details>

**Comment by ZeroMemes** [comment] 2019-04-03 00:41
Currently, tags are not supported by the command parser for blocks and items, that is a separate issue. I've fixed this issue, which is caused by unsafe usage of ``ResourceLocation``. This is fixed in the next patch.

**Closed by ZeroMemes** 2019-04-03 00:41 UTC
