### ISSUE TITLE
NoBreakDelay - Suggestion 🌟

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#708] opened 2018-09-10 02:29 UTC
Some hacked clients, or utility mods, call it what you like, have a feature that disables the delay after breaking a block. This feature is pretty much useful for servers like 2B2T and Constantiam, and may help players who use Impact. _This is the only reason why I have two utility mods installed in my computer_.

**Comment by VitorISs** [comment] 2018-09-10 02:35
Duplicate of #668

**Closed by VitorISs** 2018-09-10 02:35 UTC
Labels: Duplicate
