### ISSUE TITLE
Bring Back McLeaks Integration!

### ISSUE THREAD

**Issue by VincentCCandela** [ImpactDevelopment/ImpactClient#499] opened 2018-01-20 17:35 UTC
McLeaks integration was very helpful and I think it should be brought back because it made my life a lot easier whenever I had to use an McLeaks account. I don't know whether it was moved and i could not find it or it was permanently removed but I definitely want to be able to continue using it.

- Impact Version: <!4.1 for 1.12.1 -->
- Using Optifine? 
- Enabled mods: 
- Operating System:

**Comment by SuperOP535** [comment] 2018-01-20 18:10
Duplicating your own suggestion, very smart.
Duplicate of #113

**Closed** 2018-01-20 23:41 UTC
