### ISSUE TITLE
Block ESP

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#443] opened 2017-10-26 03:37 UTC
My idea is to add a esp for blocks, alongside with x-ray. With x-ray, yes you can choose which ores you can see, but it would be very helpful if there was an outline, and a tracer (optional) pointing to the block you need. This could be activated without x-ray to JUST see a outline and/or tracer. This would be helpful for things like finding spawners, or things that are hard to spot even with x-ray.

**Comment by ZeroMemes** [comment] 2017-10-26 03:39
Duplicate of #241

**Closed by ZeroMemes** 2017-10-26 03:39 UTC
Labels: Duplicate
