### ISSUE TITLE
Soup module

### ISSUE THREAD

**Issue by ThatGrzegorzB** [ImpactDevelopment/ImpactClient#768] opened 2018-10-18 18:53 UTC
It just doesnt work... spazzes out completly if theres soup in your inventory and you often cant turn it off even tho the module is off.

**Comment by MightyKnight** [comment] 2018-10-18 18:55
Duplicate of #580

**Closed by MightyKnight** 2018-10-18 18:55 UTC

**Comment by MightyKnight** [comment] 2018-10-18 18:56
Please search if an idea/bug was already reported before.
