### ISSUE TITLE
Reach Hack

### ISSUE THREAD

**Issue by wholesomeduck** [ImpactDevelopment/ImpactClient#869] opened 2018-11-17 16:40 UTC
### What is your suggestion?
I would like to see the implementation of a reach hack, seeing as Impact has almost every common module except this one. A range of about 20-30 blocks is very achieveable, yet very detectable, so 10+.

### Why is it useful?
Easier pvp, mob farming, etc. Also, the 6 block range on Killaura is not always useful, and reach allows you to hit on command, instead of it being automatic.

**Comment by wholesomeduck** [comment] 2018-11-17 16:42
Sorry for duplicating posts, if this is considered that.

**Comment by VitorISs** [comment] 2018-11-17 17:49
Duplicate of #211

**Closed by VitorISs** 2018-11-17 17:49 UTC
