### ISSUE TITLE
Crash when logging in via the Alt Manager

### ISSUE THREAD

**Issue by jkid291** [ImpactDevelopment/ImpactClient#98] opened 2017-08-10 20:49 UTC
I added an alt to alt list and logged in then the client crashed and would not relaunch until I deleted the alt list config file.

**Comment by LeafHacker** [comment] 2017-08-10 21:08
Can you [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests) the crash report?

It will be located in a folder called  `crash-reports` within your Impact profile folder. Usually this will be `%appdata%\.minecraft\crash-reports`.

**Comment by jkid291** [comment] 2017-08-10 21:19
There was no crash report but here is the log file (I have censored it to protect my name and others)
https://pastebin.com/gAwKxHPq

**Comment by LeafHacker** [comment] 2017-08-10 21:34
Hm strange. The log file doesn't show any errors or exceptions, and there doesn't seem to be an issue logging in.

It looks like you logged in several times, connected to a server 5 times, (successfully at least twice due to chat messages) during or after the 5th connection attempt the game stopped and exited, possibly a crash or some other termination as the exit looked pretty clean.

Does this sound correct? Can you elaborate in more detail on what you did?

---

Can you still reproduce the issue if you log in again?

The client not starting after the crash is more concerning, it might imply an exception while reading from the config file (I know @ZeroMemes seems to hate `try ... catch` blocks). Perhaps it is an issue with the new encryption?

Ordinarily I would ask you to reproduce the issue and attach a suspect config file, but the alt list may (obviously) contain private data and should be encrypted, so useless to us anyway.

---

If you can reproduce the issue any logs, including when attempting to restart the client, may be helpful.

Hopefully Brady will be able to reproduce this issue too.

**Comment by jkid291** [comment] 2017-08-10 21:36
Ok I will try to reproduce this I will keep you updated

**Comment by jkid291** [comment] 2017-08-10 23:36
Ok i have not been able to reproduce this but i found another that i have been able to do
with no alts in the alt list and nothing selected if you hit login it crashes
crash report here https://pastebin.com/EsR4S1F7

**Comment by LeafHacker** [comment] 2017-08-10 23:38
Ok, I'll close this for now since the issue can't be reproduced. Can you open a new issue for the out of bounds error when logging in with no alt selected? Thanks!

**Closed by LeafHacker** 2017-08-10 23:38 UTC
Labels: bug, need-more-info
