### ISSUE TITLE
'move around' (inventory) doesn't work (forge)

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1309] opened 2019-06-19 03:22 UTC
**Describe the bug**
'Move around' mod in 'Inventory' section doesn't work at all with forge (even in singleplayer)

**To Reproduce**
1. Run impact on forge 14.23.5.2768 (latest stable I believe)
2. Enable move around in inventory section
3. Try to move around with inventory open

**Expected behavior**
One should be able to move with his inventory open and this mod enabled

**Media**
https://streamable.com/57i55

![image](https://i.imgur.com/xSUEMqV.png)

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 
- Impact Version: 4.6 for 1.12.2 (forge)
- Using Optifine? Yes
- Using LiteLoader? No
- Enabled mods: none except inventory
- Operating System: Win 10 Pro x64 1903

</details>

**Comment by a6d6061ed1** [comment] 2019-06-19 03:40
This could be related to me installing impact on multimc instance incorrectly although I think that's unlikely because everything works except this particular mod. I'll try to do it again by following video tutorial found on wiki page of this repo.

**Comment by usereewrjrjeejr** [comment] 2019-06-19 04:22
That's a known bug btw how did you get your keyboard to show on screen?

**Comment by a6d6061ed1** [comment] 2019-06-19 04:24
> That's a known bug btw how did you get your keyboard to show on screen?

couldn't find any issues when I searched for 'inventory' or 'move around' can you reference those issues here?

keyboard overlay: [https://obsproject.com/forum/resources/input-overlay.552/](https://obsproject.com/forum/resources/input-overlay.552/ )

**Comment by usereewrjrjeejr** [comment] 2019-06-19 04:26
Might not have been reported yet

**Comment by Cerbiac** [comment] 2019-06-19 05:11
Duplicate of #1104

**Closed** 2019-06-19 05:12 UTC
Labels: Bug
