### ISSUE TITLE
Newly generated chunk tracers

### ISSUE THREAD

**Issue by Alex9303** [ImpactDevelopment/ImpactClient#600] opened 2018-05-28 02:47 UTC
All newly generated chunks would be highlighted red or any color chosen by the user.

This would be very helpful with trying to find bases.

I’m Hoping it can be added for Impact 4.3

**Comment by LeafHacker** [comment] 2018-05-28 03:06
duplicate of #555

**Closed by LeafHacker** 2018-05-28 03:06 UTC
