### ISSUE TITLE
A hack that disabled the offhand shound

### ISSUE THREAD

**Issue by Acedropthebase** [ImpactDevelopment/ImpactClient#1226] opened 2019-05-28 14:41 UTC
So on 2b2t rusher hacks has a lag machine as I call it. It spams the offhand which then sends loads of sound packets for the offhand to the player which results in lag yet if master volume is all the way down it doesn’t do any lag. Add a mod that disables the switching noise so rusher hack won’t lag us anymore.

**Comment by usereewrjrjeejr** [comment] 2019-05-28 15:56
Or just turn off your volume

**Comment by ZeroMemes** [comment] 2019-05-30 14:45
I believe the issue actually comes from the playing of the sounds, turning the sound all the way down doesn't prevent that, the sounds just aren't audible.

**Comment by 0-x-2-2** [comment] 2019-05-31 08:08
Disabling sound does work.

**Comment by Cerbiac** [comment] 2019-06-08 20:11
I think muting sound disables it. For example, muting music then unmuting it starts from the beginning of/cancels the ambient music.

**Comment by 0-x-2-2** [comment] 2019-06-10 15:50
it lags because [pozzedscode](http://www.paulscode.com) sucks.

**Comment by leijurv** [comment] 2019-07-15 21:56
Duplicate of #1295

**Closed by leijurv** 2019-07-15 21:56 UTC
Labels: Suggestion
