### ISSUE TITLE
Speed compatability with baritone

### ISSUE THREAD

**Issue by Perry1900** [ImpactDevelopment/ImpactClient#929] opened 2019-02-12 05:26 UTC
As of now, if you turn a hop speed hack on when you use baritone, it walks like norma speed unless you walk normally (I didn't check with other speed hacks).
I tried this on 2b2t but it wasn't the anticheat that prevented me from doing it (I didn't lag back), it was like I held w for half a second and then stopped for half a second.

**Comment by MastaNub** [comment] 2019-02-12 05:36
Suggest it on baritone github and not here. I like it nonetheless.

**Comment by Perry1900** [comment] 2019-02-12 11:44
Isn't britone just a feature in impact client?

**Comment by leijurv** [comment] 2019-02-12 17:38
I'm directing this back to the Impact repo since I have no way of fixing this baritone-side, since Impact is closed source.

**Comment by Perry1900** [comment] 2019-02-12 19:30
I guess only impact dev team can fix this...

**Comment by ZeroMemes** [comment] 2019-02-21 18:21
Duplicate of #730.

**Comment by leijurv** [comment] 2019-02-21 18:22
Okay. In that case the workaround would be to disable baritone's freelook I think?

**Closed by ZeroMemes** 2019-02-21 18:21 UTC
Labels: Baritone, Bug, Enhancement
