### ISSUE TITLE
Triggerbot 1.9+ cooldown

### ISSUE THREAD

**Issue by Dimitriblyater** [ImpactDevelopment/ImpactClient#635] opened 2018-07-05 16:02 UTC
Hi, please make the triggerbot compatible with MC 1.9+ attack speed

**Comment by LordQuadrato** [comment] 2018-07-06 11:32
> being able to bind \ to say stuff with a click of a button

Duplicate of  #153

Also, please only report **one** suggestion per issue. I edited your issue to make it valid.

**Comment by LordQuadrato** [comment] 2018-07-06 11:33
Also an option to synchronize the hit delay with server tps (like in killaura) would be nice.

**Comment by ZeroMemes** [comment] 2018-07-26 21:30
Added in 4.4.

**Closed by ZeroMemes** 2018-07-26 21:30 UTC
Labels: Enhancement
