### ISSUE TITLE
Freecam in mineplex causes crash

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactClient#1058] opened 2019-04-02 12:27 UTC
### What happens?
When I enable freecam in mineplex the game crashes.
### Exact steps to reproduce?

Join mineplex
enable freecam
crash

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// You're mean.

Time: 02/04/19 13:24
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at cty.a(EntityRenderer.java:944)
	at ctx.a(FogRenderer.java:143)
	at cty.b(EntityRenderer.java:1240)
	at cty.a(EntityRenderer.java:1217)
	at cty.a(EntityRenderer.java:979)
	at cft.c(SourceFile:850)
	at cft.a(SourceFile:395)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cty.a(EntityRenderer.java:944)
	at ctx.a(FogRenderer.java:143)
	at cty.b(EntityRenderer.java:1240)
	at cty.a(EntityRenderer.java:1217)

-- Affected level --
Details:
	Level name: MpServer
	All players: 19 total; [ctj['UseCodeKeem'/20215561, l='MpServer', x=0.50, y=99.50, z=-1.19], ctk['SeanOh12'/545804, l='MpServer', x=-6.80, y=99.30, z=-11.40], ctk['MovingAdventure'/508451, l='MpServer', x=6.44, y=99.00, z=10.31], ctk['warewolf_redeye'/576865, l='MpServer', x=2.34, y=99.00, z=4.78], ctk['aspee'/493439, l='MpServer', x=6.81, y=100.06, z=-1.34], ctk['Catsinator'/549774, l='MpServer', x=8.86, y=93.19, z=5.71], ctk['hugh911'/574681, l='MpServer', x=-1.91, y=103.00, z=27.18], ctk['DongOh12'/545803, l='MpServer', x=-9.41, y=99.00, z=5.66], ctk['MozzoIQ'/530754, l='MpServer', x=-8.36, y=99.22, z=-5.48], ctk['ArD_claid_Vlad'/567919, l='MpServer', x=-1.54, y=99.61, z=-5.68], ctk['ezlee6'/522378, l='MpServer', x=-2.08, y=99.00, z=1.95], ctk['PyrotechnicGod'/566968, l='MpServer', x=-8.20, y=99.61, z=-0.97], ctk['Abstractt'/566707, l='MpServer', x=-13.91, y=99.71, z=-9.52], ctk['elewen'/533726, l='MpServer', x=10.18, y=99.92, z=14.12], ctk['Julapatate'/534785, l='MpServer', x=5.18, y=99.14, z=0.49], ctk['Landay'/572970, l='MpServer', x=-2.28, y=100.00, z=11.29], ctk['Daniel2stay'/542531, l='MpServer', x=2.00, y=99.56, z=2.74], ctk['diamondchiken'/577180, l='MpServer', x=8.56, y=100.00, z=-3.81], ctk['OofieMunchkin'/547729, l='MpServer', x=-0.75, y=99.57, z=-5.53]]
	Chunk stats: MultiplayerChunkCache: 170, 170
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,100,0), Chunk: (at 0,6,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 346089 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
	Forced entities: 39 total; [ctk['MovingAdventure'/508451, l='MpServer', x=6.44, y=99.00, z=10.31], ctk['warewolf_redeye'/576865, l='MpServer', x=2.34, y=99.00, z=4.78], ctk['aspee'/493439, l='MpServer', x=6.81, y=100.06, z=-1.34], ctk['NoMercyAda'/584909, l='MpServer', x=0.50, y=99.50, z=1.50], ctk['DongOh12'/545803, l='MpServer', x=-9.41, y=99.00, z=5.66], ctk['SeanOh12'/545804, l='MpServer', x=-6.80, y=99.30, z=-11.40], ctk['Flaming_Ninja111'/584938, l='MpServer', x=0.50, y=99.50, z=1.50], ctk['Catsinator'/549774, l='MpServer', x=8.86, y=93.19, z=5.71], ctk['Catsinator'/549774, l='MpServer', x=8.86, y=93.19, z=5.71], ctk['hugh911'/574681, l='MpServer', x=-1.91, y=103.00, z=27.18], ctk['DongOh12'/545803, l='MpServer', x=-9.41, y=99.00, z=5.66], ctk['MozzoIQ'/530754, l='MpServer', x=-8.36, y=99.22, z=-5.48], ctk['ArD_claid_Vlad'/567919, l='MpServer', x=-1.54, y=99.61, z=-5.68], ctk['Julapatate'/534785, l='MpServer', x=5.18, y=99.14, z=0.49], ctk['ezlee6'/522378, l='MpServer', x=-2.08, y=99.00, z=1.95], ctk['PyrotechnicGod'/566968, l='MpServer', x=-8.20, y=99.61, z=-0.97], ctk['Abstractt'/566707, l='MpServer', x=-13.91, y=99.71, z=-9.52], ctk['ezlee6'/522378, l='MpServer', x=-2.08, y=99.00, z=1.95], ctk['elewen'/533726, l='MpServer', x=10.18, y=99.92, z=14.12], ctk['Julapatate'/534785, l='MpServer', x=5.18, y=99.14, z=0.49], ctk['Landay'/572970, l='MpServer', x=-2.28, y=100.00, z=11.29], ctk['Daniel2stay'/542531, l='MpServer', x=2.00, y=99.56, z=2.74], ctk['diamondchiken'/577180, l='MpServer', x=8.56, y=100.00, z=-3.81], ctk['OofieMunchkin'/547729, l='MpServer', x=-0.75, y=99.57, z=-5.53], ctk['diamondchiken'/577180, l='MpServer', x=8.56, y=100.00, z=-3.81], ctk['OofieMunchkin'/547729, l='MpServer', x=-0.75, y=99.57, z=-5.53], ctk['Landay'/572970, l='MpServer', x=-2.28, y=100.00, z=11.29], ctk['MovingAdventure'/508451, l='MpServer', x=6.44, y=99.00, z=10.31], ctk['PyrotechnicGod'/566968, l='MpServer', x=-8.20, y=99.61, z=-0.97], ctk['Abstractt'/566707, l='MpServer', x=-13.91, y=99.71, z=-9.52], ctk['MozzoIQ'/530754, l='MpServer', x=-8.36, y=99.22, z=-5.48], ctk['Daniel2stay'/542531, l='MpServer', x=2.00, y=99.56, z=2.74], ctk['hugh911'/574681, l='MpServer', x=-1.91, y=103.00, z=27.18], ctk['elewen'/533726, l='MpServer', x=10.18, y=99.92, z=14.12], ctk['ArD_claid_Vlad'/567919, l='MpServer', x=-1.54, y=99.61, z=-5.68], ctk['warewolf_redeye'/576865, l='MpServer', x=2.34, y=99.00, z=4.78], ctk['aspee'/493439, l='MpServer', x=6.81, y=100.06, z=-1.34], ctj['UseCodeKeem'/20215561, l='MpServer', x=0.50, y=99.50, z=-1.19], ctk['SeanOh12'/545804, l='MpServer', x=-6.80, y=99.30, z=-11.40]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCord-Bootstrap:1.13-SNAPSHOT:6c44ccd:1367) <- Mineplex Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at crg.a(WorldClient.java:576)
	at cft.b(SourceFile:1815)
	at cft.a(SourceFile:408)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 386651128 bytes (368 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2-Impact_4.6
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 419.67, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
	OptiFine Version: OptiFine_1.13.2_HD_U_E7
	OptiFine Build: 20190322-164033
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 419.67
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 1.13
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: 
```
ESP
Crosshair+
HUD
Auto chest
Anti Desync
Anti vanish
Auto cheat
Discord RPC
Criticals
Hitbox
Velocity
Franky
```
- Operating System: 

</details>

**Comment by ZeroMemes** [comment] 2019-04-02 16:16
Caused by the Night Vision potion effect that you receive in the Mineplex hub. Working on fix for both Impact 4.6 for 1.13.2 and Impact 4.6 for 1.12.2

**Comment by ZeroMemes** [comment] 2019-04-02 23:09
Fixed in the last 4.6 patch, forgot to close.

**Closed** 2019-04-02 23:08 UTC

**Comment by LeafHacker** [comment] 2019-04-02 23:16
> forgot to close.

I mean if you reference the issue in the commit it close it for you and makes a nice link for us to find the commit

**Comment by ZeroMemes** [comment] 2019-04-02 23:18
My bad I totally forgot about that feature!
