### ISSUE TITLE
1.13.2 : Tracers does not work

### ISSUE THREAD

**Issue by AstragoYT** [ImpactDevelopment/ImpactClient#1216] opened 2019-05-24 18:56 UTC

**Comment by usereewrjrjeejr** [comment] 2019-05-24 19:19
Dupe of #1189

**Comment by LeafHacker** [comment] 2019-05-24 20:29
That issue appears to have been closed without a resolution

**Comment by usereewrjrjeejr** [comment] 2019-05-24 22:05
I was being passive aggressive

**Closed** 2019-05-27 19:04 UTC
Labels: Bug
