### ISSUE TITLE
Optifine Integration

### ISSUE THREAD

**Issue by CookiePlayzGames** [ImpactDevelopment/ImpactClient#438] opened 2017-10-23 17:42 UTC
Hello Impact team, Great job so far... but you should integrate optifine.

**Comment by SuperOP535** [comment] 2017-10-23 17:45
Hello CookiePlayzGames team, Bad hob so far... you should goto https://www.youtube.com/watch?v=o1LHq6L0ibk

**Comment by VitorISs** [comment] 2017-10-23 18:23
ClientAPI isn't compatible with optifine yet

**Comment by Thunder33345** [comment] 2017-10-23 18:30
still would be nice to have that be on default/packaged with release

**Comment by ZeroMemes** [comment] 2017-10-24 02:16
There is a tutorial available for adding Optifine to Impact, however an installer should be created that allows users to install it into Optifine.

**Comment by SuperOP535** [comment] 2017-10-24 14:44
The reason is that the creator of OptiFine has not allowed anyone to use it in their versions (license stuff I guess?) (not sure)

**Comment by ZeroMemes** [comment] 2017-10-25 21:56
I don't believe the license permits redistribution, I didn't want to risk anything.

**Comment by ZeroMemes** [comment] 2017-10-25 21:58
Closing due to duplicate of #88. Opened an issue for an installer (#440).

**Closed by ZeroMemes** 2017-10-25 21:58 UTC
Labels: Duplicate, OptiFine
