### ISSUE TITLE
automine bug

### ISSUE THREAD

**Issue by niggish** [ImpactDevelopment/ImpactClient#1161] opened 2019-04-23 00:37 UTC
**Describe the bug**
turning on `auto mine` module and switching to `log` crashes me. launching my game and trying to login a server also crashes me.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
The game crashed whilst ticking entity
The game crashed whilst ticking entity
Error: java.lang.NullPointerException: Ticking entity
```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
https://hastebin.com/uladifomiv.rb
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>

- Impact Version: `4.6 for 1.13.2`
- Using Optifine? `yes`
- Using LiteLoader? `no`
- Enabled mods: `auto mine`
- Operating System: `windows 10 64-bit`

**Comment by leijurv** [comment] 2019-04-23 00:53
what is the output of `.b version`

**Comment by niggish** [comment] 2019-04-24 19:04
`.b version` is v1.3.1

**Comment by leijurv** [comment] 2019-04-24 19:05
<img width="708" alt="Screen Shot 2019-04-24 at 12 05 15 PM" src="https://user-images.githubusercontent.com/3837873/56686623-3d821a00-6689-11e9-9f3e-31897b65ec9d.png">
add this url parameter back to your version json (dont forget the comma)

this is fixed in version 1.3.2

**Comment by leijurv** [comment] 2019-04-24 19:06
Will look into this, and release a new version soon ish

**Comment by leijurv** [comment] 2019-04-24 19:11
Cannot reproduce at all

**Comment by niggish** [comment] 2019-04-24 19:17
https://streamable.com/sy5jl

**Comment by leijurv** [comment] 2019-04-24 19:26
just tried exactly this, and it worked fine

reinstall the json i guess?

**Comment by leijurv** [comment] 2019-05-29 05:52
this is just not the case lmao

**Closed by leijurv** 2019-05-29 05:52 UTC
Labels: Bug
