### ISSUE TITLE
Avatar moves while in freecam

### ISSUE THREAD

**Issue by CrypticCalamari** [ImpactDevelopment/ImpactClient#672] opened 2018-08-02 07:20 UTC
Recently freecam has been causing my avatar to move with the camera when freecamming. This only happens initially and seems to stop when the avatar collides with a wall, but this makes it inconvenient to freecam when there are no walls around, because the server thinks I'm flying and kicks me requiring me to restart the client before logging back in.

Not sure if this has been happening like this the whole time, or if this is something new. There's no crash involved, so I'm not sure what to provide. No other movement or player options are active when this happens.

**Comment by LeafHacker** [comment] 2018-08-02 09:19
Think this got introduced when I was fixing other freecam stuff in 4.3.

We probably aren't canceling all the client movement packets.

_Seeing_ the avatar movement is intended though, as I deliberately forward server movement packets to the avatar. This was originally so that wandering horses would behave as intended (if the player is sat on one without a saddle), but has the added benefit of making bugs like this easier to spot.

**Comment by ZeroMemes** [comment] 2018-09-19 02:16
This has been fixed in 4.4. It was due to a bad listener target caused by a method reference not being properly resolved, lol @LeafHacker

**Closed by ZeroMemes** 2018-09-19 02:16 UTC
Labels: Bug
