### ISSUE TITLE
Executing Baritone's "damn" command runs fine, but causes Impact to output an invalid syntax warning.

### ISSUE THREAD

**Issue by SylveonBottle** [ImpactDevelopment/ImpactClient#842] opened 2018-10-28 23:51 UTC
https://github.com/cabaletta/baritone/blob/master/src/main/java/baritone/utils/ExampleBaritoneControl.java#L451

![aehgqa 1](https://user-images.githubusercontent.com/17802843/47623682-6c587280-dae2-11e8-998b-e238f80b483b.png)

Steps to reproduce:

1. Execute `.b damn`

**Comment by ZeroMemes** [comment] 2018-10-28 23:51
LOL

**Comment by leijurv** [comment] 2018-10-28 23:52
LOL

**Comment by SuperOP535** [comment] 2018-10-30 16:11
BIGGEST BUG NEEDS TO BE SOLVED __NOW__

**Comment by leijurv** [comment] 2018-11-01 21:12
This is so that you can still say `damn` in chat on baritone standalone (with no prefix). (i.e. it's intended behavior that saying damn in baritone standalone gets passed through to chat, AND baritone also responds to it with `daniel`) Therefore, this is a wontfix from the baritone side, but Impact could still detect the `damn` message and not print the invalid syntax message even though ExampleBaritoneControl returns false.

**Comment by ZeroMemes** [comment] 2019-02-24 05:20
Go away

**Comment by leijurv** [comment] 2019-02-25 21:18
Fixed in 4.6

**Closed by leijurv** 2019-02-25 21:18 UTC
Labels: Baritone, Bug, Critical
