### ISSUE TITLE
macros dont work

### ISSUE THREAD

**Issue by f1Lthz4** [ImpactDevelopment/ImpactClient#1166] opened 2019-04-23 16:45 UTC
Cant use any macros at all,
cant erase any text in macro editor,
cant type anything in the 2nd row when creating/editing macro 

tried fully reinstalling impact with removing mixin and impact folders (had old config files from 2017 so thought it could mess smth up)

<details>

- Impact Version: 4.6 for 1.13.2
- Using Optifine? tried both with optifine and without
- Using LiteLoader? No
- Operating System: Windows 10 64bit

</details>

**Comment by LeafHacker** [comment] 2019-05-24 20:55
Duplicate of #954

**Closed by LeafHacker** 2019-05-24 20:55 UTC
Labels: Bug
