### ISSUE TITLE
Minestrike Glitch

### ISSUE THREAD

**Issue by daggerdig** [ImpactDevelopment/ImpactClient#178] opened 2017-08-28 07:55 UTC
In minestrike some players i see are not highlighted in the minestrike ESP. The aimbot does not shoot at entities that are not highlighted.

**Comment by Discoli** [comment] 2017-08-28 15:00
Yea, I reported this to brady a whiiiiiiiiiile back before 4.0, I get this too.

**Comment by ZeroMemes** [comment] 2017-08-30 19:30
@Discoli That was caused by another issue. This is different.

I believe that the issue has been fixed, after I made a modification to the code the issue hasn't been occurring anymore. Closing for now.

**Closed by ZeroMemes** 2017-08-30 19:30 UTC
Labels: Bug

**Comment by ZeroMemes** [comment] 2017-08-30 19:58
Also duplicate of #143
