### ISSUE TITLE
Alt manager Bug 1. 

### ISSUE THREAD

**Issue by Pabsb** [ImpactDevelopment/ImpactClient#578] opened 2018-05-01 00:08 UTC
Alt Manager shows emails off to side:

![https://gyazo.com/ea10692bedeef12db8296916b9b8975b](https://i.gyazo.com/ea10692bedeef12db8296916b9b8975b.png)

<details> 
  <summary>FOV</summary>
 
![https://gyazo.com/a7c2a351d31f6da818cd7e1aeef18429](https://i.gyazo.com/a7c2a351d31f6da818cd7e1aeef18429.png)

</details>

<details> 
  <summary>Video settings</summary>
 
![https://gyazo.com/e55dee32b3dfc1f9589c2b7986fe94c0](https://i.gyazo.com/e55dee32b3dfc1f9589c2b7986fe94c0.png)

</details>

### Exact steps to reproduce?
Run impact 1.12.2
Click alt button.

### Additional Client Info
- Impact Version: 4.2
- Using Optifine? No
- Operating System: Windows 10 64bit
- Resolution: 2560 x 1440
- [Userbenchmark](http://www.userbenchmark.com/UserRun/8548190)

Since issue #577 didn't have all information New one with all proper info made. #577 Can be closed.

**Comment by LeafHacker** [comment] 2018-05-09 18:00
Thank you for re-posting this issue with additional detail, however I am going to close this as a duplicate of #577.

Instead of competing with some other user's issue, you should have instead posted any related information as a comment on the relevant issue.

Closed is not deleted: should we require any of the detail here, we can always refer back to it.

**Closed by LeafHacker** 2018-05-09 18:00 UTC
