### ISSUE TITLE
Add McLeaks!!

### ISSUE THREAD

**Issue by BradleyCrazy** [ImpactDevelopment/ImpactClient#559] opened 2018-04-26 22:41 UTC
Please Add McLeaks Again :(

**Comment by LeafHacker** [comment] 2018-04-26 22:52
MCLeaks is present in 4.2

**Comment by LeafHacker** [comment] 2018-04-26 22:52
Marking as duplicate of #113

**Closed by LeafHacker** 2018-04-26 22:52 UTC
Labels: Invalid

**Comment by BradleyCrazy** [comment] 2018-04-26 23:01
OK Ty
