### ISSUE TITLE
Clicking period opens chat and puts two ".." in chat.

### ISSUE THREAD

**Issue by MastaNub** [ImpactDevelopment/ImpactClient#1031] opened 2019-03-25 12:37 UTC
### What happens?
The title.

### Exact steps to reproduce?

Hit period.

**Comment by LeafHacker** [comment] 2019-03-25 13:37
Intended behaviour is that it opens chat and types a single `.`. Are you sure you're not somehow double clicking or holding down the key?

**Comment by LeafHacker** [comment] 2019-03-25 13:41
Never mind, able to reproduce on my machine

**Comment by LeafHacker** [comment] 2019-03-25 13:53
Caused by a 1.13 change to how key events are handled. We now need to cancel key events we've handled or Minecraft will handle them after us too.

**Comment by LeafHacker** [comment] 2019-03-25 14:03
Fixed in 4.6 (next beta patch or whatever)

**Closed** 2019-03-25 14:03 UTC
Labels: Bug
