### ISSUE TITLE
pig speedhack and jesus

### ISSUE THREAD

**Issue by a6d6061ed1** [ImpactDevelopment/ImpactClient#1306] opened 2019-06-18 15:38 UTC
**Is your feature request related to a problem? Please describe.**
there are two problems with riding pig while using jesus and entity speed. first one is that for jesus to actually work with pig, it needs to be already submerged in water when you mount it. it can get annoying after sometime of travelling on mixed terrain. 

second issue is that when speedhacking on pig with jesus enabled you can (rarely) get killed instantly. Although its really inconsistent and probably related to anticheat that server is running I suspect that solution for this exists.

**Describe the solution you'd like**
improve jesus / riding mod to fix those issues

**Comment by Cerbiac** [comment] 2019-06-18 15:52
The jesus x riding issue is a Duplicate of #1233.
However, IDK about the pig killing you as you ride it. As only the mount would die from fall damage, what is the kill message?

**Comment by a6d6061ed1** [comment] 2019-06-18 16:57
> The jesus x riding issue is a Duplicate of #1233.
> However, IDK about the pig killing you as you ride it. As only the mount would die from fall damage. What is the death message? I bet it is the anticheat killing you.

don't know what death messages is because I always had totem on me. sometimes me/pig can take damage without dying and sometimes me and my pig just die instantly. it could be related to the same problem as antihunger effective + jesus (you take fall damage when touching water). and I think that if it was anticheat doing it deliberately it wouldn't be so inconsistent

**Comment by Cerbiac** [comment] 2019-06-18 17:13
Anti Hunger might be the cause. I'll look into it.

**Comment by a6d6061ed1** [comment] 2019-06-18 17:14
> Anti Hunger might be the cause. I'll look into it.

yes I had smart antihunger enabled what that happened. this might be related

**Comment by 0-x-2-2** [comment] 2019-06-18 18:58
One suggestion/bug per case.

**Comment by 0-x-2-2** [comment] 2019-06-18 18:59
One suggestion/bug per issue.

**Closed by 0-x-2-2** 2019-06-18 18:58 UTC
Labels: Suggestion

**Comment by Cerbiac** [comment] 2019-06-18 19:11
Well, there is only one issue to be addressed, the other is a duplicate and already has been resolved, so is fine.
