### ISSUE TITLE
Jesus Not Working Properly with Rideable Entities

### ISSUE THREAD

**Issue by WaffleTraits** [ImpactDevelopment/ImpactClient#1091] opened 2019-04-07 04:11 UTC
When you enable jesus while on land and mount an entity, it will sink in water instead of walking on top of it. Player has to have jesus enabled and be on the water prior to mounting the entity in order for it to function. See video for demonstration: https://streamable.com/bespp

### What happens?

Jesus doesnt work properly with rideable entities.
### Exact steps to reproduce?

- Step one: Enable Jesus on land and mount entity.
- Step two: Move entity over body of water.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 
- Using Optifine?  Yes
- Using LiteLoader?  No
- Enabled mods: Jesus, solid mode.
- Operating System:  Windows 10 64bit

</details>

**Comment by Cerbiac** [comment] 2019-06-18 15:51
Duplicate of #1233

**Comment by Cerbiac** [comment] 2019-06-18 15:57
Well, actually this was the original, but ehh.

**Comment by 0-x-2-2** [comment] 2019-06-18 19:04
Closing for a better issue. #1233

**Closed by 0-x-2-2** 2019-06-18 19:04 UTC
