### ISSUE TITLE
Elytra+ prevents water from removing kinetic energy

### ISSUE THREAD

**Issue by lmaolmao123123** [ImpactDevelopment/ImpactClient#60] opened 2017-08-05 19:42 UTC
I just almost died crashing into WATER with an ELYTRA while using ELYTRA+ on VANILLA... Rip..

**Comment by MagicSenpai** [comment] 2017-08-05 19:42
OMG SAME!?!?!?!?!?!?!?1

**Comment by MagicSenpai** [comment] 2017-08-05 19:42
BUT I DID DIE

**Comment by LeafHacker** [comment] 2017-08-05 19:58
Can't reproduce. Pretty sure moderator oli and magic are spamming...............

Closing for now

**Comment by LeafHacker** [comment] 2017-08-05 21:26
Managed to reproduce by flying into stone at a funny angle through the edge of water with elytra+.

**Closed** 2018-04-20 19:26 UTC
Labels: Bug
