### ISSUE TITLE
Auto-Respawn doesn't work (EntityDeathEvent not triggered)

### ISSUE THREAD

**Issue by VitorISs** [ImpactDevelopment/ImpactClient#147] opened 2017-08-23 23:32 UTC
When I have auto-respawn active and I die, it doesn't respawn me..
The screen "You died!" remains.

**Comment by LeafHacker** [comment] 2017-08-24 03:26
Looks like this is caused by `EntityDeathEvent` not being fired on death. Needs some further investigation for now, we'll try and get this fixed in time for 4.1 today.

**Comment by LeafHacker** [comment] 2017-08-24 04:13
Fixed in 4.1.

This was caused by ImpactDevelopment/ClientAPI/issues/25. For now we work around the issue by listening to `TickEvent` instead and checking if the player is dead every tick.

**Closed by LeafHacker** 2017-08-24 04:13 UTC
Labels: Bug
