### ISSUE TITLE
BowAimbot freezes game

### ISSUE THREAD

**Issue by InstantReflex** [ImpactDevelopment/ImpactClient#107] opened 2017-08-14 02:04 UTC
Whenever I activate bow aimbot and start to charge my bow, my game turns black and freezes. Simple as that. Pretty much everyone has already reported this, so I know its not my fault. Plez fix this :(

**Comment by ZeroMemes** [comment] 2017-08-14 02:22
Duplicate of #85, closing.

**Closed** 2017-08-14 02:23 UTC
