### ISSUE TITLE
NoPush hack.

### ISSUE THREAD

**Issue by TheCookCola** [ImpactDevelopment/ImpactClient#585] opened 2018-05-05 21:43 UTC
The NoPush disables when I join the game.

### What happens?
Every time that I join Minecraft, the NoPush disables itself.

### When does this happen?
Every time I open Minecraft.

### Exact steps to reproduce?

  Toggle on NoPush
  Quit Minecraft
  Rejoin Minecraft
   No Push is disabled

**Comment by VitorISs** [comment] 2018-05-05 21:59
duplicate of #258 
already fixed in 4.2

**Closed** 2018-05-05 21:59 UTC
Labels: Duplicate
