### ISSUE TITLE
LiteLoader is Incompatible with the Forge Version of Impact

### ISSUE THREAD

**Issue by n3rt46** [ImpactDevelopment/ImpactClient#1232] opened 2019-05-30 19:43 UTC
**Describe the bug**
LiteLoader and Forge, as well as their own respective mods, work together fine. When trying to use Impact with LiteLoader and Forge, however, the client crashes during startup.

**To Reproduce**
1. Using MultiMC, create a new instance on 1.12.2
2. Click "Edit Instance"
4. Click "Version," then click "Install Forge," and "Install LiteLoader." Use the default version for both.
3. If LiteLoader is set to be loaded after Forge, select LiteLoader and then click "Move up" (otherwise, the client will crash during startup).
5. In the main MultiMC window, click "Minecraft Folder," this will open a window to the created instance's Minecraft folder. Copy it's path.
4. Using the Impact client installer, change the Minecraft directory to the path you copied, and then choose to install for Forge, then click "Install."
7. Back in MultiMC, click "Launch"

**Expected behavior**
The Minecraft client should have started and opened the client window.

<details> 
  <summary><strong>Game output</strong></summary>
 

```
MultiMC version: 0.6.5-1302


Minecraft folder is:
B:/Applications/MultiMC/instances/Test/.minecraft


Java path is:
C:/Program Files/Java/jre1.8.0_211/bin/javaw.exe


Java is version 1.8.0_211, using 64-bit architecture.


Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  B:/Applications/MultiMC/instances/Test/natives

Libraries:
  B:/Applications/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  B:/Applications/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  B:/Applications/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  B:/Applications/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  B:/Applications/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  B:/Applications/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  B:/Applications/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  B:/Applications/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  B:/Applications/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  B:/Applications/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  B:/Applications/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  B:/Applications/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  B:/Applications/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  B:/Applications/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  B:/Applications/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  B:/Applications/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  B:/Applications/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  B:/Applications/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  B:/Applications/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  B:/Applications/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  B:/Applications/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  B:/Applications/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  B:/Applications/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  B:/Applications/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  B:/Applications/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  B:/Applications/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  B:/Applications/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  B:/Applications/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  B:/Applications/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  B:/Applications/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  B:/Applications/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  B:/Applications/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  B:/Applications/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  B:/Applications/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar
  B:/Applications/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
  B:/Applications/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  B:/Applications/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  B:/Applications/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  B:/Applications/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  B:/Applications/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  B:/Applications/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  B:/Applications/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  B:/Applications/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  B:/Applications/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  B:/Applications/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  B:/Applications/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  B:/Applications/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  Impact-4.6-1.12.2

Params:
  --username  --version MultiMC5 --gameDir B:/Applications/MultiMC/instances/Test/.minecraft --assetsDir B:/Applications/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass com.mumfrey.liteloader.launch.LiteLoaderTweaker --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8192m, -Duser.language=en]


Minecraft process ID: 6016


Using onesix launcher.

[14:40:23] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[14:40:23] [main/INFO]: Using primary tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[14:40:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:40:23] [main/INFO]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[14:40:23] [main/INFO]: Bootstrapping LiteLoader 1.12.2
[14:40:23] [main/INFO]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[14:40:23] [main/INFO]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[14:40:23] [main/INFO]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[14:40:23] [main/INFO]: Initialising API 'liteloader' ...
[14:40:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/B:/Applications/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar Service=LaunchWrapper Env=CLIENT
[14:40:23] [main/INFO]: LiteLoader begin PREINIT...
[14:40:23] [main/INFO]: Initialising Loader properties...
[14:40:23] [main/INFO]: Setting up logger...
[14:40:23] [main/INFO]: LiteLoader 1.12.2 starting up...
[14:40:23] [main/INFO]: Active Pack: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
[14:40:23] [main/INFO]: Java reports OS="windows 10"
[14:40:23] [main/INFO]: Adding supported mod class prefix 'LiteMod'
[14:40:23] [main/INFO]: Enumerating class path...
[14:40:23] [main/INFO]: Class path separator=";"
[14:40:23] [main/INFO]: Class path entries=(
   classpathEntry=B:/Applications/MultiMC/jars/NewLaunch.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
   classpathEntry=B:/Applications/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
   classpathEntry=B:/Applications/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
   classpathEntry=B:/Applications/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mumfrey/liteloader/1.12.2-SNAPSHOT/liteloader-1.12.2-SNAPSHOT.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-universal.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
   classpathEntry=B:/Applications/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
   classpathEntry=B:/Applications/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
   classpathEntry=B:/Applications/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar
)
[14:40:23] [main/INFO]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[14:40:23] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [B:\Applications\MultiMC\instances\Test\.minecraft\mods]
[14:40:23] [main/INFO]: Registering discovery module EnumeratorModuleFolder: [B:\Applications\MultiMC\instances\Test\.minecraft\mods\1.12.2]
[14:40:23] [main/INFO]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@57f791c6]
[14:40:23] [main/INFO]: Discovering valid mod files in folder B:\Applications\MultiMC\instances\Test\.minecraft\mods
[14:40:23] [main/INFO]: Inspecting jar metadata in 'Impact-4.6-1.12.2.jar'
[14:40:23] [main/INFO]: Ignoring B:\Applications\MultiMC\instances\Test\.minecraft\mods\Impact-4.6-1.12.2.jar
[14:40:23] [main/INFO]: Discovering valid mod files in folder B:\Applications\MultiMC\instances\Test\.minecraft\mods\1.12.2
[14:40:23] [main/INFO]: Discovering tweaks on class path...
[14:40:23] [main/INFO]: Baking listener list for EnumerationObserver with 1 listeners
[14:40:23] [main/INFO]: Registering discovered mod files in folder B:\Applications\MultiMC\instances\Test\.minecraft\mods
[14:40:23] [main/INFO]: Registering discovered mod files in folder B:\Applications\MultiMC\instances\Test\.minecraft\mods\1.12.2
[14:40:23] [main/INFO]: Initialising LiteLoader Mixins
[14:40:23] [main/INFO]: Compatibility level set to JAVA_8
[14:40:23] [main/INFO]: LiteLoader PREINIT complete
[14:40:23] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[14:40:23] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[14:40:23] [main/INFO]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[14:40:23] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[14:40:23] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[14:40:23] [main/INFO]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[14:40:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:40:23] [main/INFO]: Forge Mod Loader version 14.23.5.2768 for Minecraft 1.12.2 loading
[14:40:23] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_211
[14:40:23] [main/INFO]: Searching B:\Applications\MultiMC\instances\Test\.minecraft\mods for mods
[14:40:23] [main/INFO]: Searching B:\Applications\MultiMC\instances\Test\.minecraft\mods\1.12.2 for mods
[14:40:23] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Impact-4.6-1.12.2.jar
[14:40:23] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:40:23] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[14:40:23] [main/INFO]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker$PreInitTweaker
[14:40:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:40:23] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[14:40:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:40:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:40:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:40:23] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[14:40:23] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@547c04c4
[14:40:23] [main/WARN]: Mixin config mixins.capi.json requires mixin subsystem version 0.7.8 but 0.7.5 was found. The mixin config will not be applied.
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.capi.json requires mixin subsystem version 0.7.8
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:282)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:56)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:103)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:146)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanClasspath(MixinPlatformManager.java:230)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:199)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:189)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:40:23] [main/INFO]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[14:40:23] [main/INFO]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[14:40:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.6 for 1.12.2
- Using Optifine: No
- Using LiteLoader: Yes
- Enabled mods: N/A (Default)
- Operating System: Windows 10 Pro 64bit

</details>

**Additional context**
Quite frankly, the only reason I'm interested in using LiteLoader in the first place is to use a single mod: World Downloader. World Downloader works fine as a jar mod with vanilla Impact, but using World Downloader with Forge or OptiFine causes lots of problems.

**Comment by leijurv** [comment] 2019-05-30 21:43
Why forge?

**Comment by n3rt46** [comment] 2019-05-30 21:55
Well, I'm using Forge so that I can use Schematica, OptiFine, and BBOR, if that's what you mean.

**Comment by 0-x-2-2** [comment] 2019-05-31 08:00
Duplicate of #1145

**Closed by 0-x-2-2** 2019-05-31 08:00 UTC
Labels: Bug
