### ISSUE TITLE
Weird NullPointerException which happens only when I try to join 2b

### ISSUE THREAD

**Issue by EvilSourcerer** [ImpactDevelopment/ImpactClient#983] opened 2019-03-07 23:38 UTC
Disconnect error : https://pastebin.com/ms1zHVu0

Modules enabled : https://cdn.discordapp.com/attachments/514880901629607947/553358369499643934/unknown.png

**Comment by EvilSourcerer** [comment] 2019-03-07 23:39
to reproduce just try to connect 2b with the modules i have enabled sorry for having you to enable modules hopefully the disconnect error is helpful

**Comment by LeafHacker** [comment] 2019-03-07 23:45
Could you attach your `Impact/config/default.json` as this will give us your exact config?

**Comment by EvilSourcerer** [comment] 2019-03-07 23:46
sure
[default.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2943809/default.txt)

**Comment by FliegendeWurst** [comment] 2019-03-08 14:10
I'm also getting this error sometimes. It's usually enough to reconnect a few times.

**Comment by EvilSourcerer** [comment] 2019-03-08 16:06
but why is this... It's been a thing for literally years.

**Comment by ZeroMemes** [comment] 2019-03-09 07:09
God I'm an idiot, fixed in 4.6, caused by log position!

**Closed by ZeroMemes** 2019-03-09 07:09 UTC

**Comment by leijurv** [comment] 2019-03-09 21:51
log position be like
