### ISSUE TITLE
Add true durability 

### ISSUE THREAD

**Issue by Infernopickaxe** [ImpactDevelopment/ImpactClient#1011] opened 2019-03-21 12:43 UTC
For armor and tools that go above the normal durability amount as in 2b2t's "unbreakables" (not really unbreakable)
I would like it if it displays in the armor hud, hovering over the item, and seeing it in player name tags
(I believe the items have a high negative damage value)

**Comment by LeafHacker** [comment] 2019-03-21 14:17
Minecraft doesn't support modifying the durability of a tool, so the concept of a higher durability tool doesn't make sense.

Instead items have a damage value which counts up until maxDamage is reached and the item is destroyed.

I suspect that maybe you are talking about enchantments, perhaps the item has a high level Unbreaking enchantment or something?

**Comment by Infernopickaxe** [comment] 2019-03-21 14:31
No I'm talking about durability 
Another client already has true durability 
On 2b2t we have "unbreakables" the durability of these items are in the thousands (max being the original durability + 32767)

**Comment by LeafHacker** [comment] 2019-03-21 15:37
That doesn't make sense. The -32,768 to +32,767 is a 16bit `short`, which enchantment levels are stored as. However `damage` and `maxDamage` are both stored as 32bit `int`s which has a range of -2,147,483,648 to +2,147,483,647 ("durability" remaining is calculated on the fly as `maxDamage - damage`).

I'd love to see a screenshot/gif/video/whatever of one of these items, or a `/give` command of how they were originally hacked in (and in which version).

**Comment by Infernopickaxe** [comment] 2019-03-21 15:40
Do you have a discord?

**Comment by LeafHacker** [comment] 2019-03-21 15:42
Yes, [here](https://discordapp.com/invite/SXdUEe). Btw this probably a duplicate of #957

**Comment by Infernopickaxe** [comment] 2019-03-21 15:44
Yeah I just joined in github I didnt see that one

**Comment by LeafHacker** [comment] 2019-03-21 15:46
np it wouldn't have been easy to find since damage/durability isn't in the title. Anyway back on topic do you have anything showing the characteristics of these items? Have you interacted with these yourself or simply heard about them somewhere (if so where)?

**Comment by Infernopickaxe** [comment] 2019-03-21 15:48
Trying to find the screenshot

**Comment by Infernopickaxe** [comment] 2019-03-21 16:21
https://cdn.discordapp.com/attachments/208753003996512258/558317352605843476/20190321_105311.png
Add an extra line on the tooltip similar to this for damage information

**Comment by LeafHacker** [comment] 2019-03-21 23:17
I don't think this adds anything that the vanilla game doesn't already do. Vanilla already shows `Durability: 3204/1561`, the only thing added in the screenshot is the damage `(-1643)` which is `- durability + maxDamage` (since `durability = maxDamage - damage`)

**Comment by leijurv** [comment] 2019-03-22 18:38
Added in 4.6

**Closed by leijurv** 2019-03-22 18:38 UTC
Labels: Enhancement, GUI
