### ISSUE TITLE
Config loader

### ISSUE THREAD

**Issue by JoeTheThird** [ImpactDevelopment/ImpactClient#1211] opened 2019-05-23 01:20 UTC
It would be cool if i could have as many configs as i like, one for legit, one for servers with friends, and one for anarchy servers. It would be very helpful instead of changing my config for every time i do a different server.

**Comment by ThebesAndSound** [comment] 2019-05-23 13:23
You can do this with multimc and the impact forge version, your different instances can have different impact configurations. Thats how I do it anyway.

**Comment by LeafHacker** [comment] 2019-05-24 16:53
Even the vanilla launcher allows you to duplicate profiles and set different run directories for each.

This is a duplicate of #450 and #219 though

**Closed by LeafHacker** 2019-05-24 16:53 UTC
