### ISSUE TITLE
NCP fly completely useless.

### ISSUE THREAD

**Issue by SuperOP535** [ImpactDevelopment/ImpactClient#170] opened 2017-08-27 11:45 UTC
Once enabled auto kicks you from the server it doesn't even work in singleplayer!! I get kicked for Invalid player move packet recieved... After this I have to change it in mods.json because I can't join a singleplayer world while this is on (same error as server gives)

**Comment by zPeanut** [comment] 2017-08-27 12:27
has been already issued.

**Comment by zPeanut** [comment] 2017-08-27 12:28
duplicate of #51

**Closed by zPeanut** 2017-08-27 12:28 UTC
Labels: Bug, Duplicate, Removed
