### ISSUE TITLE
player character unable to move or change direction

### ISSUE THREAD

**Issue by MercilessArchitect** [ImpactDevelopment/ImpactClient#1217] opened 2019-05-24 20:35 UTC
Describe the bug:
whenever i move, after a few seconds it sends me back to where i was, and my character goes back to the direction it was facing. /killing myself just locks into a new position.
the issue appears on multiple servers on both 1.12 and 1.13, as well as singleplayer worlds.
i had to completely reinstall both minecraft and impact to get rid of the issue

To Reproduce:
go on a singleplayer world.
go to the nether.
turn on no fall.
drop down roughly 50 blocks.
you will die
success.

Expected behavior:*
your player character will be able to move, but after a second or so every time your character will be reset to its previous position. running /kill leaves your character in the same locked position
the issue will persist across multiple servers and worlds, it persisted overnight, too

**Comment by LeafHacker** [comment] 2019-05-24 20:48
Duplicate of #1213

**Closed by LeafHacker** 2019-05-24 20:48 UTC
Labels: Bug
