### ISSUE TITLE
AutoReconnect reconnects instantly after getting kicked from the server

### ISSUE THREAD

**Issue by MischievousMoo** [ImpactDevelopment/ImpactClient#468] opened 2017-11-13 01:39 UTC
AutoReconnect will instantly reconnect, regardless of how much time specified. This creates problems with servers that kick you if you reconnect too quickly.

### What happens?

I don't get shown the reconnect screen, and the "Connecting to the server..." message instantly pops up after getting disconnected.
### When does this happen?

When I get kicked from a server with autoreconnect already on. It will be normal if I turn on AutoReconnect from the disconnected screen, but it will skip the delay if I get kicked while it's already on.
### Exact steps to reproduce?

1. Join a server
2. Turn on or have autoreconnect enabled
3. Get kicked from the server
4. Watch yourself get reconnected instantly

- Impact Version: 4.1 for 1.12.2
- Using Optifine? No
- Enabled mods: Autoreconnect 5143ms, Respawn, Middle click friend, Velocity 0%, Anti overlay, ItemPhysics, Trajectories, CameraClip, ESP Shader, Nametags, ItemSaver, No Rotate, Anti Blind, Tracers, Light
- Operating System: Windows 10

**Comment by InstantReflex** [comment] 2017-12-04 02:25
Works fine for me :/ Don't know what the problem is. What version of Impact are you encountering this problem in?

**Comment by Thunder33345** [comment] 2017-12-04 03:19
> What version of Impact are you encountering this problem in?

>Impact Version: 4.1 for 1.12.2

**Comment by LeafHacker** [comment] 2018-02-15 23:56
Fixed in 4.2

**Closed by LeafHacker** 2018-02-15 23:56 UTC
Labels: Bug
