### ISSUE TITLE
IRC module

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#689] opened 2018-08-14 00:17 UTC
Back in the day Nodus had an IRC feature that allowed you to talk to players who had the same hacked client. It was useful to find teammates in minigames, distract by talking to each other  and get support from other players. It even allowed me back in 2011 to discover some servers I still play this day.  Related image:
<img src="https://vgy.me/6tJmJ0.jpg" alt="6tJmJ0.jpg">

**Comment by ZeroMemes** [comment] 2018-08-14 00:18
Duplicate of #124

**Closed by ZeroMemes** 2018-08-14 00:18 UTC
