### ISSUE TITLE
[Suggestion] FastBridge option for safewalk

### ISSUE THREAD

**Issue by SigmaRS** [ImpactDevelopment/ImpactClient#922] opened 2019-02-07 14:06 UTC
### What is your suggestion?

An option to automatically sneak when you're at the edges of a block while using SafeWalk.

### Why is it useful?

It would be useful to play _legit_ on minigame servers.

**Comment by leijurv** [comment] 2019-02-07 18:26
Duplicate of #898

**Closed by leijurv** 2019-02-07 18:26 UTC
