### ISSUE TITLE
server error..

### ISSUE THREAD

**Issue by takabakouti** [ImpactDevelopment/ImpactClient#693] opened 2018-08-16 07:05 UTC
### Exact steps to reproduce?

- Step one
server login
- Another step
move...(waiting..?)
  - Note about "Another step"
- A third step
![2018-08-16 15 31 59](https://user-images.githubusercontent.com/42430477/44192449-63563700-a16a-11e8-982f-0ef4201efff6.png)

- etc

<details> 
  <summary><strong>Game output</strong></summary>

```

```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
4.3(now 1.12.2)
- Using Optifine? 
yes
- Enabled mods: 
![2018-08-16 15 44 48](https://user-images.githubusercontent.com/42430477/44192682-5a199a00-a16b-11e8-9f00-cd711fae8c2b.png)

- Operating System: 
macOS High Sierra 64bit

</details>

**Comment by 0-x-2-2** [comment] 2018-08-16 07:07
Can you give your logs/game output?

**Comment by LordQuadrato** [comment] 2018-08-16 07:11
Duplicate of #658

**Closed by LordQuadrato** 2018-08-16 07:11 UTC
Labels: Bug, Need more info
