### ISSUE TITLE
[Time Consuming]Basic Implementation of a Script API.

### ISSUE THREAD

**Issue by mrphax0r** [ImpactDevelopment/ImpactClient#1340] opened 2019-07-08 17:40 UTC
**Is your feature request related to a problem? Please describe.**
There are many things an Individual might want to have in Impact that are too small to be Implemented by Devs. Also, if they get added, this costs time the Devs would like to spend on other things.

**Describe the solution you'd like**
A basic Scripting API may be a solution that is worth considering. This way, individuals can customize Impact even further to their liking.

**Describe alternatives you've considered**
Stealing time from the Devs, or not implementing the small modules at all.

**Additional context**
*Coding such an API takes time and should therefore be considered in the future.*

**Comment by ScanmanTM** [comment] 2019-07-09 14:36
Possible dupe of #911 ?

**Closed** 2019-07-10 11:36 UTC
Labels: Duplicate, Suggestion

**Comment by mrphax0r** [comment] 2019-07-10 19:29
Ye that's what i meant
