### ISSUE TITLE
Crash on gnu/linux

### ISSUE THREAD

**Issue by ViniDalvino** [ImpactDevelopment/ImpactClient#899] opened 2019-01-02 19:39 UTC
### What happens?
My client crash randomely when I play normally(with cheat). I am on Gnu/Linux if that can help. I provide the file of cheat enabled. I also provide others crash report aswell.

### Exact steps to reproduce?
It happen randomely when I am playing. However this never happen when I am into the queue of 2b2t.  I suggest trying out on a gnu/linux machine since I play on Gnu/Linux.
<details> 
  <summary><strong>Game output</strong></summary>
 

```
14:14:57 | bjb | [CHAT] Position in queue: 25
-- | -- | --
14:15:07 | bjb | [CHAT] Position in queue: 25
14:15:17 | bjb | [CHAT] Position in queue: 25
14:15:27 | bjb | [CHAT] Position in queue: 25
14:15:35 | no | [STDOUT]: World save took 0ms
14:15:37 | bjb | [CHAT] Position in queue: 25
14:15:47 | bjb | [CHAT] Position in queue: 25
14:15:57 | bjb | [CHAT] Position in queue: 25
14:16:07 | bjb | [CHAT] Position in queue: 24
14:16:17 | bjb | [CHAT] Position in queue: 24
14:16:27 | bjb | [CHAT] Position in queue: 23
14:16:37 | bjb | [CHAT] Position in queue: 23
14:16:47 | bjb | [CHAT] Position in queue: 21
14:16:57 | bjb | [CHAT] Position in queue: 21
14:17:07 | bjb | [CHAT] Position in queue: 21
14:17:17 | bjb | [CHAT] Position in queue: 21
14:17:27 | bjb | [CHAT] Position in queue: 21
14:17:37 | bjb | [CHAT] Position in queue: 20
14:17:47 | bjb | [CHAT] Position in queue: 20
14:17:57 | bjb | [CHAT] Position in queue: 20
14:18:07 | bjb | [CHAT] Position in queue: 20
14:18:17 | bjb | [CHAT] Position in queue: 20
14:18:27 | bjb | [CHAT] Position in queue: 20
14:18:37 | bjb | [CHAT] Position in queue: 20
14:18:47 | bjb | [CHAT] Position in queue: 20
14:18:57 | bjb | [CHAT] Position in queue: 20
14:19:07 | bjb | [CHAT] Position in queue: 20
14:19:17 | bjb | [CHAT] Position in queue: 20
14:19:27 | bjb | [CHAT] Position in queue: 19
14:19:37 | bjb | [CHAT] Position in queue: 19
14:19:47 | bjb | [CHAT] Position in queue: 19
14:19:57 | bjb | [CHAT] Position in queue: 19
14:20:07 | bjb | [CHAT] Position in queue: 19
14:20:17 | bjb | [CHAT] Position in queue: 19
14:20:27 | bjb | [CHAT] Position in queue: 19
14:20:37 | bjb | [CHAT] Position in queue: 18
14:20:43 | bjb | [CHAT] Connecting to the server...
14:20:50 | no | [STDOUT]: Baritone world data dir: /home/vincent/.minecraft/baritone/2b2t.org/DIM-1
14:20:50 | no | [STDOUT]: Started saving the world in a new thread
14:20:50 | no | [STDOUT]: World save took 0ms
14:20:50 | no | [STDOUT]: Cached world directory: /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:20:50 | no | [STDOUT]: Would save waypoints to /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/waypoints
14:20:50 | no | [STDOUT]: Loading region -18,0 from disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:20:51 | no | [STDOUT]: Loaded region successfully in 469ms
14:20:51 | no | [STDOUT]: Loading region -18,-1 from disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:20:51 | no | [STDOUT]: Loaded region successfully in 424ms
14:20:55 | j | Loaded 218 advancements
14:20:59 | bjb | [CHAT] <RusherB0T> Hello 2b2t! This is a very useful chatbot. Use !help to see my various commands.
14:20:59 | bjb | [CHAT] <Razpaq> reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
14:21:00 | bjb | [CHAT] <BlasterXX> server ded
14:21:18 | bjb | [CHAT] <ViniDalvino> !que
14:21:20 | no | [STDOUT]: Saving region -18,0 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:21:20 | no | [STDOUT]: Saving region -18,-1 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:21:21 | no | [STDOUT]: Saved region successfully
14:21:21 | no | [STDOUT]: Saved region successfully
14:21:21 | no | [STDOUT]: World save took 284ms
14:21:23 | bjb | [CHAT] [Debug]: Reloading all chunks
14:21:26 | bjb | [CHAT] <EatKFC> > Good bye, Dnamite.
14:21:27 | bjb | [CHAT] <Yqe> the chat is a little spammed with joined messages
14:21:27 | bjb | [CHAT] <Therecreep> beat the queue jumped 99 spots
14:21:29 | bjb | [CHAT] <SpawnFag> dont kill me
14:21:33 | bjb | [CHAT] <Yqe> the chat is a little spammed with joined messages
14:21:33 | bjb | [CHAT] <IHacked2b2tps> wtf
14:21:33 | bjb | [CHAT] <EatKFC> > See you next time, RedChocolateCake.
14:21:33 | bjb | [CHAT] <Nagoy777> that was lag
14:21:33 | bjb | [CHAT] <Hungary> asd
14:21:35 | bjb | [CHAT] [Impact] Graffen has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] Areogast has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] maddhatterzs has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] kerm77 has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] shadowstorm110 has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] Mukler has gone into vanish mode!
14:21:35 | bjb | [CHAT] <EatKFC> > Catch ya later, Kahszzear.
14:21:35 | bjb | [CHAT] <The_Explorer_123> !help
14:21:35 | bjb | [CHAT] [Impact] patches8178 has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] TrollMuff has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] iAreLuck has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] RobertTheRed01 has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] Creator06 has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] DineWithOdin has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] iMems has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] RusherB0T has gone into vanish mode!
14:21:35 | bjb | [CHAT] [Impact] Hanzo_Autism has gone into vanish mode!
14:21:35 | bjb | [CHAT] <EatKFC> > Catch ya later, iMems.
14:21:35 | bjb | [CHAT] <Rekmix> lag?
14:21:35 | bjb | [CHAT] <orugez21> !que
14:21:36 | bjb | [CHAT] <Yqe> t
14:21:36 | bjb | [CHAT] <EatKFC> > Catch ya later, Rethkan.
14:21:39 | bjb | [CHAT] [Impact] RusherB0T has gone out of vanish mode!
14:21:40 | no | [STDOUT]: Started saving the world in a new thread
14:21:40 | no | [STDOUT]: Saving region -19,-1 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:21:40 | bib | Unreported exception thrown! java.util.ConcurrentModificationException 	at java.util.ArrayList.forEach(ArrayList.java:1260) 	at me.zero.clarinet.bU.lambda$new$5(bU.java) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93) 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99) 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99) 	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44) 	at bib.handler$preRunTick$zzp000(SourceFile:3174) 	at bib.t(SourceFile) 	at bib.az(SourceFile:1000) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
14:21:40 | no | [STDOUT]: Saving region -19,0 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
09:21:40 | game | ---- Minecraft Crash Report ---- // Oh - I know what I did wrong!  Time: 1/2/19 2:21 PM Description: Unexpected error  java.util.ConcurrentModificationException 	at java.util.ArrayList.forEach(ArrayList.java:1260) 	at me.zero.clarinet.bU.lambda$new$5(bU.java) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93) 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99) 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99) 	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44) 	at bib.handler$preRunTick$zzp000(SourceFile:3174) 	at bib.t(SourceFile) 	at bib.az(SourceFile:1000) 	at bib.a(SourceFile:419) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Client thread Stacktrace: 	at java.util.ArrayList.forEach(ArrayList.java:1260) 	at me.zero.clarinet.bU.lambda$new$5(bU.java) 	at me.zero.alpine.listener.Listener.invoke(Listener.java:93) 	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99) 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891) 	at me.zero.alpine.bus.EventManager.post(EventManager.java:99) 	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44) 	at bib.handler$preRunTick$zzp000(SourceFile:3174)  -- Affected level -- Details: 	Level name: MpServer 	All players: 1 total; [bud['ViniDalvino'/1498, l='MpServer', x=-9226.59, y=120.00, z=0.29]] 	Chunk stats: MultiplayerChunkCache: 81, 81 	Level seed: 0 	Level generator: ID 00 - default, ver 1. Features enabled: false 	Level generator options:  	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511) 	Level time: 169425 game time, 1496702074 day time 	Level dimension: 0 	Level storage version: 0x00000 - Unknown? 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false) 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false 	Forced entities: 1 total; [bud['ViniDalvino'/1498, l='MpServer', x=-9226.59, y=120.00, z=0.29]] 	Retry entities: 0 total; [] 	Server brand: Waterfall (git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238) <- Paper 	Server type: Non-integrated multiplayer server Stacktrace: 	at bsb.a(SourceFile:366) 	at bib.b(SourceFile:2587) 	at bib.a(SourceFile:433) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:498) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)  -- System Details -- Details: 	Minecraft Version: 1.12.2 	Operating System: Linux (amd64) version 4.18.5-041805-generic 	Java Version: 1.8.0_191, Oracle Corporation 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 262977520 bytes (250 MB) / 469762048 bytes (448 MB) up to 3221225472 bytes (3072 MB) 	JVM Flags: 7 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=100M 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 	Launched Version: 1.12.2-Impact_4.4 	LWJGL: 2.9.4 	OpenGL: Mesa DRI Mobile Intel® GM45 Express Chipset  GL version 2.1 Mesa 18.2.2, Intel Open Source Technology Center 	GL Caps: Using GL 1.3 multitexturing. Using GL 1.3 texture combiners. Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported. Shaders are available because OpenGL 2.1 is supported. VBOs are available because OpenGL 1.5 is supported.  	Using VBOs: No 	Is Modded: Very likely; Jar signature invalidated 	Type: Client (map_client.txt) 	Resource Packs:  	Current Language: English (US) 	Profiler Position: N/A (disabled) 	CPU: 2x Intel(R) Core(TM)2 Duo CPU T6400 @ 2.00GHz #@!@# Game crashed! Crash report saved to: #@!@# /home/vincent/.minecraft/crash-reports/crash-2019-01-02_14.21.40-client.txt   <log4j:Event logger="no" timestamp="1546456900766" level="INFO" thread="ForkJoinPool.commonPool-worker-0">     <log4j:Message><![CDATA[[STDOUT]: Saved region successfully]]></log4j:Message>   </log4j:Event>
09:21:40 | monitor | expected <
14:21:40 | no | [STDOUT]: Saved region successfully
14:21:40 | no | [STDOUT]: Saving region -18,-1 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:21:40 | no | [STDOUT]: Saving region -18,0 to disk /home/vincent/.minecraft/baritone/2b2t.org/DIM-1/cache
14:21:41 | launcher | AL lib: (EE) alc_cleanup: 1 device not closed pure virtual method called terminate called without an active exception
09:21:41 | monitor | Process crashed with exit code 6


```

</details>

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/2/19 2:21 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at me.zero.clarinet.bU.lambda$new$5(bU.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bib.handler$preRunTick$zzp000(SourceFile:3174)
	at bib.t(SourceFile)
	at bib.az(SourceFile:1000)
	at bib.a(SourceFile:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at me.zero.clarinet.bU.lambda$new$5(bU.java)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.bus.EventManager.lambda$post$5(EventManager.java:99)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at me.zero.alpine.bus.EventManager.post(EventManager.java:99)
	at clientapi.event.ClientAPIEventManager.post(ClientAPIEventManager.java:44)
	at bib.handler$preRunTick$zzp000(SourceFile:3174)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [bud['ViniDalvino'/1498, l='MpServer', x=-9226.59, y=120.00, z=0.29]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 169425 game time, 1496702074 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [bud['ViniDalvino'/1498, l='MpServer', x=-9226.59, y=120.00, z=0.29]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238) <- Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at bsb.a(SourceFile:366)
	at bib.b(SourceFile:2587)
	at bib.a(SourceFile:433)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.18.5-041805-generic
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262977520 bytes (250 MB) / 469762048 bytes (448 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 7 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=100M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2-Impact_4.4
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Mobile Intel® GM45 Express Chipset  GL version 2.1 Mesa 18.2.2, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU T6400 @ 2.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/vincent/.minecraft/crash-reports/crash-2019-01-02_14.21.40-client.txt
  <log4j:Event logger="no" timestamp="1546456900766" level="INFO" thread="ForkJoinPool.commonPool-worker-0">
    <log4j:Message><![CDATA[[STDOUT]: Saved region successfully]]></log4j:Message>
  </log4j:Event>
```
Here is as well other crash report since it happen quite frequently. 
[crash-2018-12-24_15.11.10-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721777/crash-2018-12-24_15.11.10-client.txt)
[crash-2018-12-24_20.41.15-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721778/crash-2018-12-24_20.41.15-client.txt)
[crash-2018-12-24_20.43.40-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721779/crash-2018-12-24_20.43.40-client.txt)
[crash-2018-12-24_21.18.13-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721780/crash-2018-12-24_21.18.13-client.txt)
[crash-2018-12-24_21.54.12-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721781/crash-2018-12-24_21.54.12-client.txt)

[crash-2018-12-24_22.57.24-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721782/crash-2018-12-24_22.57.24-client.txt)
[crash-2018-12-25_16.33.14-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721783/crash-2018-12-25_16.33.14-client.txt)
[crash-2018-12-25_18.17.09-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721784/crash-2018-12-25_18.17.09-client.txt)
[crash-2018-12-25_19.38.53-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721785/crash-2018-12-25_19.38.53-client.txt)
[crash-2018-12-25_20.51.48-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721786/crash-2018-12-25_20.51.48-client.txt)
[crash-2018-12-25_23.08.28-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721787/crash-2018-12-25_23.08.28-client.txt)
[crash-2018-12-25_23.17.26-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721788/crash-2018-12-25_23.17.26-client.txt)
[crash-2018-12-26_21.27.46-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721789/crash-2018-12-26_21.27.46-client.txt)
[crash-2018-12-26_21.49.54-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721790/crash-2018-12-26_21.49.54-client.txt)
[crash-2018-12-27_22.11.10-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721791/crash-2018-12-27_22.11.10-client.txt)
[crash-2018-12-28_19.32.27-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721792/crash-2018-12-28_19.32.27-client.txt)
[crash-2018-12-29_19.37.42-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721793/crash-2018-12-29_19.37.42-client.txt)
[crash-2018-12-29_20.08.33-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721794/crash-2018-12-29_20.08.33-client.txt)
[crash-2018-12-31_18.56.07-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721795/crash-2018-12-31_18.56.07-client.txt)
[crash-2018-12-31_19.31.46-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721796/crash-2018-12-31_19.31.46-client.txt)
[crash-2019-01-01_10.56.07-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721797/crash-2019-01-01_10.56.07-client.txt)
[crash-2019-01-01_15.02.06-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721798/crash-2019-01-01_15.02.06-client.txt)
[crash-2019-01-02_13.31.56-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721799/crash-2019-01-02_13.31.56-client.txt)
[crash-2019-01-02_14.21.40-client.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721800/crash-2019-01-02_14.21.40-client.txt)

</details>

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 4.4 for 1.12.1
- Using Optifine? No
- Using LiteLoader? No 
- Enabled mods: [default.txt](https://github.com/ImpactDevelopment/ImpactClient/files/2721768/default.txt)
- Operating System: Nitrux 1.0.15
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 262977520 bytes (250 MB) / 469762048 bytes (448 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 7 total; -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -
</details>

**Comment by MightyKnight** [comment] 2019-01-02 20:07
Duplicate of #835. Please disable `Anti Vanish`.

**Closed by MightyKnight** 2019-01-02 20:07 UTC
