### ISSUE TITLE
Glitched TTF rendering at higher font sizes

### ISSUE THREAD

**Issue by hugohindi** [ImpactDevelopment/ImpactClient#217] opened 2017-09-07 15:26 UTC
![Photo](https://i.imgur.com/DK4eacv.png)
WHY IS THERE A DOT THERE NOW I CANT USE IMPACT ANYMORE

**Comment by ZeroMemes** [comment] 2017-09-07 21:21
Caused by bad TTF rendering. It was covered up by a rectangle for the 4.0 release, Leaf accidentally removed it for 4.1

**Comment by ZeroMemes** [comment] 2018-01-20 06:29
Fixed in 4.2

**Closed by ZeroMemes** 2018-01-20 06:29 UTC
Labels: Bug

**Comment by VitorISs** [comment] 2018-01-20 06:43
nice, impact will be playable again
