### ISSUE TITLE
No SRP

### ISSUE THREAD

**Issue by Drottt** [ImpactDevelopment/ImpactClient#607] opened 2018-06-02 07:25 UTC
This option is something from Podcrash+.
No SRP removes servers forced pack, which keeps you from freezing for some time when leaving/joining a game.
This helps people with bad laptops or computers, like me to actually play the game. 
If No SRP were to be added, multiple people would use the utility mod more without hesitation.
I hope you consider my idea, as I am looking forward to using Impact and watching it grow stronger and bigger.

**Comment by LordQuadrato** [comment] 2018-06-02 09:57
Duplicate of #593.

**Closed** 2018-06-02 09:58 UTC
Labels: Duplicate
