### ISSUE TITLE
Portal ESP

### ISSUE THREAD

**Issue by RohanG0407** [ImpactDevelopment/ImpactClient#598] opened 2018-05-27 03:28 UTC
### Add a .search command which creates tracers to portal blocks or any block so its easy to identify where portals are

![image](https://user-images.githubusercontent.com/24467483/40582202-6af645cc-613c-11e8-9a43-15a2ec2bce86.png)

**Comment by LeafHacker** [comment] 2018-05-27 03:33
Duplicate of #241

**Closed by LeafHacker** 2018-05-27 03:33 UTC
