### ISSUE TITLE
Freecam moves the schematic

### ISSUE THREAD

**Issue by mastatrue** [ImpactDevelopment/ImpactClient#1109] opened 2019-04-10 19:24 UTC
I load a schematic and when I try to view it on freecam, the schematic moves with the camera. It happens on the forge version. I tried with no hacks and it's still doing it

**Comment by 0-x-2-2** [comment] 2019-04-11 22:28
Is this schematica?

**Comment by mastatrue** [comment] 2019-04-11 23:21
It happens only with impact so I don't think is schematica related

**Comment by 0-x-2-2** [comment] 2019-04-12 01:12
>I don't think is schematica related. 
How are you loading a schematic then?

**Comment by mastatrue** [comment] 2019-04-12 08:51
I said in the first posts, it happens only with impact forge. For example the freecam in forgehax doesn't interfere with schematica

**Comment by 0-x-2-2** [comment] 2019-04-14 01:51
I am just asking if you are using schematica or not.

**Comment by ZeroMemes** [comment] 2019-04-14 02:34
Duplicate of #1107

**Closed by ZeroMemes** 2019-04-14 02:34 UTC
Labels: Bug, Forge

**Comment by leijurv** [comment] 2019-08-23 01:54
https://discordapp.com/channels/208753003996512258/378646935302701070/614274322596364298
