### ISSUE TITLE
Impact Client crashes using LiteLoader

### ISSUE THREAD

**Issue by EmeraldSnorlax** [ImpactDevelopment/ImpactClient#917] opened 2019-01-28 16:43 UTC
Installed using [this link](http://www.liteloader.com/download#snapshot_11220l). Tried the .exe on Windows 10, and the .jar on openSUSE tumbleweed.

Here is the error output:

![image](https://user-images.githubusercontent.com/43452521/51850851-8c364700-231a-11e9-84b0-070531d2385a.png)
(Same error on 'Weed as on 'Doze)

Installation settings:
![image](https://user-images.githubusercontent.com/43452521/51850933-b7b93180-231a-11e9-93f0-74ba878f01f0.png)
(Again, same on 'doze)

### What happens?

Crashes Immediately on startup.
### Exact steps to reproduce?
Install Impact 4.4 for 1.12.2
Install Liteloader on top of Impact 4.4
The game launcher itself gives no output.

  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version: 
Impact 4.4 for 1.12.2
- Using Optifine? 
Nope. 
- Using LiteLoader? 
Uh, Liteloader is whats making Impact crash...
- Enabled mods: 
No enabled mods as the client doesn't even start
- Operating System: 
Both Windows 10 64x and openSUSE Tumbleweed, using Java8 for both.

Edit: Failed grammar

**Comment by NotGeri** [comment] 2019-01-30 08:00
Same problem here. 
No crash-report, the only thing I can show is the conzole's log.
https://pastebin.com/QeZxVnwk


Impact 4.4 for 1.12.2
Using Optifine
Trying to use Liteloader
No enabled mods as the client doesn't even start
Windows 10 Pro 64x

**Comment by ZeroMemes** [comment] 2019-02-09 20:28
**This isn't an issue caused by Impact**, this is a LiteLoader problem. When the version JSON is created by LiteLoader, it specifies an older mixin version (0.7.5) which is older than the required version (0.7.8) by ClientAPI. Impact requires even a higher version last time I checked (0.7.11).

The fix for this is to navigate to the JSON that liteloader created in your Minecraft install directory and set the 0.7.5 Mixin version set by LiteLoader to a higher version, **0.7.11 should work.**

**Closed by ZeroMemes** 2019-02-09 20:28 UTC
Labels: Crash

**Comment by ZeroMemes** [comment] 2019-02-09 20:59
My bad, because LiteLoader is a fat jar, the Mixin version it uses is bundled into the jar itself. Here are the steps to fix:

### 1) Delete the Mixin version from the LiteLoader jar

Delete the "org" folder in the root directory of the LiteLoader jar, it should only contain Mixin so this will be fine. Mine is already deleted.

![image](https://user-images.githubusercontent.com/24485393/52526197-e4eed380-2c7a-11e9-99fb-87880ad29887.png)

### 2) Remove the URL from the LiteLoader JSON

This will prevent the LiteLoader jar from being "fixed" and having the Mixin version restored. Again, mine is already deleted. Below is what it should look like once removed.

![image](https://user-images.githubusercontent.com/24485393/52526233-34cd9a80-2c7b-11e9-9255-e770420ed389.png)
