### ISSUE TITLE
EntitySpeed

### ISSUE THREAD

**Issue by zPeanut** [ImpactDevelopment/ImpactClient#97] opened 2017-08-08 12:18 UTC
title says it all

**Comment by LeafHacker** [comment] 2017-08-08 13:18
@zPeanut When you mark something as a duplicate you should close it and leave a message saying "Duplicate of #issue":

**Comment by LeafHacker** [comment] 2017-08-08 13:19
Duplicate of #77

**Closed by LeafHacker** 2017-08-08 13:19 UTC
Labels: duplicate, feature-request
