### ISSUE TITLE
ClickCycler doesn't render the tooltip

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactClient#549] opened 2018-04-23 20:03 UTC
Despite calling the tooltip method, it doesn't get drawn for multi value cyclers... Likely either an issue with checking if the mouse is inside<sup>[1]</sup> or an early return I missed in the ClickCycler render method.

<sup>[1]</sup> The tooltip timer gets reset whether the mouse isn't inside

**Comment by ZeroMemes** [comment] 2018-04-23 22:02
Caused by the description not being set in the first place. Fixed in 4.3.

**Closed by ZeroMemes** 2018-04-23 22:02 UTC
Labels: Bug, GUI
