### ISSUE TITLE
Name tag and Tracer module don’t  work

### ISSUE THREAD

**Issue by WomasL** [ImpactDevelopment/ImpactClient#512] opened 2018-03-11 12:42 UTC
### What happens?

The tracer and name tag module doesn’t draw line or detailed name tag. The vanilla nametag disappeared too. The impact is with optifine. I tried many options including turn off fast render but non of them works. Even without optifine, it doesn’t work.

### Exact steps to reproduce?
Unreproduceable

- Step one
- Another step
  - Note about "Another step"
- A third step
- etc

### Game output?

```

```

### Crash report?

```

```

- Impact Version: Impact 4.1 for 1.12.2 with optifine
- Using Optifine?  Yes
- Enabled mods: 
- Operating System:  Window 10 64bit

**Comment by VitorISs** [comment] 2018-03-11 17:24
duplicate of #137 
just turn off fast render

**Comment by ZeroMemes** [comment] 2018-03-22 20:14
Can confirm this is a duplicate of #137, continue the conversation over there if needed.

**Closed by ZeroMemes** 2018-03-22 20:14 UTC
