### ISSUE TITLE
Antihunger makes you die

### ISSUE THREAD

**Issue by DeeFeeCee** [ImpactDevelopment/ImpactClient#1086] opened 2019-04-06 09:07 UTC
### What happens?
Player takes damage for no good reason. This issue is compounded by the SPEED-block edge issue I submitted earlier.

### Exact steps to reproduce?
The easiest way I've found to replicate this issue is to activate AntiHunger & run & jump onto a lily pad. This can take away 5 hearts with full iron armor. It can also insta-kill. I've experienced this when jumping down. Hard to replicate the other happenings, though.

<details> 
  <summary><strong>Additional Client Info</strong></summary>
 

- Impact Version:  4.6 for 1.12.2
- Using Optifine?  Yes (doesn't matter)
- Using LiteLoader?  No
- Enabled mods:  AntiHunger (compounds with Speed & possibly No Fall, Spider, Jesus, & No Slow (water))
- Operating System:  Win10 64b

</details>

**Comment by LeafHacker** [comment] 2019-04-06 13:23
This is caused by the way the server handles things. It is a fundamental part of antihunger and cannot be fixed. Duplicate of #702

**Closed by LeafHacker** 2019-04-06 13:23 UTC

**Comment by DeeFeeCee** [comment] 2019-04-06 16:15
What do you mean by it's the way the server handles things? (Not trying to be rude; want to understand.) This happens even offline.

**Comment by 0-x-2-2** [comment] 2019-04-06 17:15
🦍

**Comment by 0-x-2-2** [comment] 2019-04-06 17:15
singleplayer is a local server btw

**Comment by DeeFeeCee** [comment] 2019-04-06 17:20
So 1.12.2 just screws with people. Nice.

**Comment by LeafHacker** [comment] 2019-04-06 19:10
> So 1.12.2 just screws with people. Nice.

no, 1.12.2 just doesn't expect us to try and avoid taking hunger... it expects the client to behave like the vanilla client and tell it whether it is onground or not.

**Comment by DeeFeeCee** [comment] 2019-04-06 22:47
Then is antiHunger sending incorrect onground info? Is that how it reduces starvation?

**Comment by leijurv** [comment] 2019-04-06 22:50
Yep, it just reports onGround as false to the server that's it
